/*  Java Native Interrface code generated by apiwrapper for GAMS Version 24.7.4 */

#include <jni.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
/* #include <locale.h> */
#include <gmdcc.h>

/* at least for some JNI implementations, JNIEXPORT is not setup to
 * explicitly set visibility to default when using GNU compilers;
 * thus, we do this globally for all functions via this pragma
 *  (which is nicer than redefining JNIEXPORT)
 */
#ifdef __GNUC__
#pragma GCC visibility push(default)
#endif

typedef union foo { void *p; jlong i; } u64_t;

typedef char string255[256];
typedef char stringUEL[GLOBAL_UEL_IDENT_SIZE];


static void printerr(const char *mess, const char*name)
{
   fprintf(stderr,"%s: %s\n",mess,name);
   exit(1);
}

static JavaVM *Cached_JVM = NULL;
JNIEXPORT jint JNICALL JNI_OnLoad(JavaVM *vm, void *reserved)
{
    Cached_JVM = vm;
    gmdInitMutexes();
    return JNI_VERSION_1_2;
}

JNIEXPORT void JNICALL JNI_OnUnload(JavaVM *vm, void *reserved)
{
    gmdFiniMutexes();
}

static char* getMethodName_(const char* name)
{
    char *s;
    s = strrchr(name,'.');
    if (s==NULL)
        return NULL;
    ++s;
    return strdup(s);
}

static char* getClassName_(const char* name)
{
    char *s;
    char *t;
    t = strdup(name);
    s = strrchr(t,'.');
    if (s==NULL)
        return NULL;
    *s = '\0';
    return t;
}

JNIEXPORT jint JNICALL Java_com_gams_api_gmd_GetReady(JNIEnv *env, jobject obj, jobjectArray msg);
JNIEXPORT jint JNICALL Java_com_gams_api_gmd_GetReady(JNIEnv *env, jobject obj, jobjectArray msg)
{
   int rc_GetReady;
   jstring local_msg;
   char buffer_msg[256];
   rc_GetReady = gmdGetReady(buffer_msg, sizeof(buffer_msg));
   local_msg = (*env)->NewStringUTF(env, buffer_msg);
   (*env)->SetObjectArrayElement(env, msg, 0, local_msg);
   return rc_GetReady;
}

JNIEXPORT jint JNICALL Java_com_gams_api_gmd_GetReadyD(JNIEnv *env, jobject obj, jstring dirName, jobjectArray msg);
JNIEXPORT jint JNICALL Java_com_gams_api_gmd_GetReadyD(JNIEnv *env, jobject obj, jstring dirName, jobjectArray msg)
{
   int rc_GetReadyD;
   char *local_dirName;
   jstring local_msg;
   char buffer_msg[256];
   buffer_msg[0] = '\0';
   local_dirName = (char *) (*env)->GetStringUTFChars(env, dirName, NULL);
   rc_GetReadyD = gmdGetReadyD(local_dirName, buffer_msg, sizeof(buffer_msg));
   (*env)->ReleaseStringUTFChars(env, dirName, local_dirName);
   local_msg = (*env)->NewStringUTF(env, buffer_msg);
   (*env)->SetObjectArrayElement(env, msg, 0, local_msg);
   return rc_GetReadyD;
}

JNIEXPORT jint JNICALL Java_com_gams_api_gmd_GetReadyL(JNIEnv *env, jobject obj, jstring libName, jobjectArray msg);
JNIEXPORT jint JNICALL Java_com_gams_api_gmd_GetReadyL(JNIEnv *env, jobject obj, jstring libName, jobjectArray msg)
{
   int rc_GetReadyL;
   char *local_libName;
   jstring local_msg;
   char buffer_msg[256];
   buffer_msg[0] = '\0';
   local_libName = (char *) (*env)->GetStringUTFChars(env, libName, NULL);
   rc_GetReadyL = gmdGetReadyL(local_libName, buffer_msg, sizeof(buffer_msg));
   (*env)->ReleaseStringUTFChars(env, libName, local_libName);
   local_msg = (*env)->NewStringUTF(env, buffer_msg);
   (*env)->SetObjectArrayElement(env, msg, 0, local_msg);
   return rc_GetReadyL;
}

JNIEXPORT jint JNICALL Java_com_gams_api_gmd_Create(JNIEnv *env, jobject obj, jobjectArray msg);
JNIEXPORT jint JNICALL Java_com_gams_api_gmd_Create(JNIEnv *env, jobject obj, jobjectArray msg)
{
   int rc_Create;
   jfieldID fid;
   u64_t pgmd;
   jstring local_msg;
   char buffer_msg[256];
   jclass cls = (*env)->GetObjectClass(env, obj);
   buffer_msg[0] = '\0';
   fid = (*env)->GetFieldID(env, cls, "gmdPtr", "J");
   if (fid == NULL) return 0;
   pgmd.i = (*env)->GetLongField(env, obj, fid);
   rc_Create = gmdCreate((gmdHandle_t *)&pgmd.p, buffer_msg, sizeof(buffer_msg));
   local_msg = (*env)->NewStringUTF(env, buffer_msg);
   (*env)->SetObjectArrayElement(env, msg, 0, local_msg);
   (*env)->SetLongField(env, obj, fid, pgmd.i);
   return rc_Create;
}

JNIEXPORT jint JNICALL Java_com_gams_api_gmd_CreateD(JNIEnv *env, jobject obj, jstring dirName, jobjectArray msg);
JNIEXPORT jint JNICALL Java_com_gams_api_gmd_CreateD(JNIEnv *env, jobject obj, jstring dirName, jobjectArray msg)
{
   int rc_CreateD;
   jfieldID fid;
   u64_t pgmd;
   char *local_dirName;
   jstring local_msg;
   char buffer_msg[256];
   jclass cls = (*env)->GetObjectClass(env, obj);
   buffer_msg[0] = '\0';
   fid = (*env)->GetFieldID(env, cls, "gmdPtr", "J");
   if (fid == NULL) return 0;
   pgmd.i = (*env)->GetLongField(env, obj, fid);
   local_dirName = (char *) (*env)->GetStringUTFChars(env, dirName, NULL);
   rc_CreateD = gmdCreateD((gmdHandle_t *)&pgmd.p, local_dirName, buffer_msg, sizeof(buffer_msg));
   (*env)->ReleaseStringUTFChars(env, dirName, local_dirName);
   local_msg = (*env)->NewStringUTF(env, buffer_msg);
   (*env)->SetObjectArrayElement(env, msg, 0, local_msg);
   (*env)->SetLongField(env, obj, fid, pgmd.i);
   return rc_CreateD;
}

JNIEXPORT jint JNICALL Java_com_gams_api_gmd_CreateDD(JNIEnv *env, jobject obj, jstring dirName, jobjectArray msg);
JNIEXPORT jint JNICALL Java_com_gams_api_gmd_CreateDD(JNIEnv *env, jobject obj, jstring dirName, jobjectArray msg)
{
   int rc_CreateDD;
   jfieldID fid;
   u64_t pgmd;
   char *local_dirName;
   jstring local_msg;
   char buffer_msg[256];
   jclass cls = (*env)->GetObjectClass(env, obj);
   buffer_msg[0] = '\0';
   fid = (*env)->GetFieldID(env, cls, "gmdPtr", "J");
   if (fid == NULL) return 0;
   pgmd.i = (*env)->GetLongField(env, obj, fid);
   local_dirName = (char *) (*env)->GetStringUTFChars(env, dirName, NULL);
   rc_CreateDD = gmdCreateDD((gmdHandle_t *)&pgmd.p, local_dirName, buffer_msg, sizeof(buffer_msg));
   (*env)->ReleaseStringUTFChars(env, dirName, local_dirName);
   local_msg = (*env)->NewStringUTF(env, buffer_msg);
   (*env)->SetObjectArrayElement(env, msg, 0, local_msg);
   (*env)->SetLongField(env, obj, fid, pgmd.i);
   return rc_CreateDD;
}

JNIEXPORT jint JNICALL Java_com_gams_api_gmd_CreateL(JNIEnv *env, jobject obj, jstring libName, jobjectArray msg);
JNIEXPORT jint JNICALL Java_com_gams_api_gmd_CreateL(JNIEnv *env, jobject obj, jstring libName, jobjectArray msg)
{
   int rc_CreateL;
   jfieldID fid;
   u64_t pgmd;
   char *local_libName;
   jstring local_msg;
   char buffer_msg[256];
   jclass cls = (*env)->GetObjectClass(env, obj);
   buffer_msg[0] = '\0';
   fid = (*env)->GetFieldID(env, cls, "gmdPtr", "J");
   if (fid == NULL) return 0;
   pgmd.i = (*env)->GetLongField(env, obj, fid);
   local_libName = (char *) (*env)->GetStringUTFChars(env, libName, NULL);
   rc_CreateL = gmdCreateL((gmdHandle_t *)&pgmd.p, local_libName, buffer_msg, sizeof(buffer_msg));
   (*env)->ReleaseStringUTFChars(env, libName, local_libName);
   local_msg = (*env)->NewStringUTF(env, buffer_msg);
   (*env)->SetObjectArrayElement(env, msg, 0, local_msg);
   (*env)->SetLongField(env, obj, fid, pgmd.i);
   return rc_CreateL;
}

JNIEXPORT jint JNICALL Java_com_gams_api_gmd_Free(JNIEnv *env, jobject obj);
JNIEXPORT jint JNICALL Java_com_gams_api_gmd_Free(JNIEnv *env, jobject obj)
{
   int rc_Free;
   jfieldID fid;
   u64_t pgmd;
   jclass cls = (*env)->GetObjectClass(env, obj);
   fid = (*env)->GetFieldID(env, cls, "gmdPtr", "J");
   if (fid == NULL) return 0;
   pgmd.i = (*env)->GetLongField(env, obj, fid);
   rc_Free = gmdFree((gmdHandle_t *)&pgmd.p);
   (*env)->SetLongField(env, obj, fid, pgmd.i);
   return rc_Free;
}


JNIEXPORT jboolean JNICALL Java_com_gams_api_gmd_InitFromGDX(JNIEnv *env, jobject obj, jstring fileName)
{
   int rc_gmdInitFromGDX;
   jfieldID fid;
   u64_t pgmd;
   jclass cls = (*env)->GetObjectClass(env, obj);
   char *local_fileName;
   fid = (*env)->GetFieldID(env, cls, "gmdPtr", "J");
   if (fid == NULL) return 0;
   pgmd.i = (*env)->GetLongField(env, obj, fid);
   local_fileName = (char *)(*env)->GetStringUTFChars(env, fileName, NULL);
   rc_gmdInitFromGDX = gmdInitFromGDX((gmdHandle_t)pgmd.p, local_fileName);
   (*env)->ReleaseStringUTFChars(env, fileName, local_fileName);
   return rc_gmdInitFromGDX;
}

JNIEXPORT jboolean JNICALL Java_com_gams_api_gmd_InitFromDict(JNIEnv *env, jobject obj, jlong gmoPtr)
{
   int rc_gmdInitFromDict;
   jfieldID fid;
   u64_t pgmd;
   jclass cls = (*env)->GetObjectClass(env, obj);
   u64_t local_gmoPtr;
   fid = (*env)->GetFieldID(env, cls, "gmdPtr", "J");
   if (fid == NULL) return 0;
   pgmd.i = (*env)->GetLongField(env, obj, fid);
   local_gmoPtr.i = gmoPtr;
   rc_gmdInitFromDict = gmdInitFromDict((gmdHandle_t)pgmd.p, local_gmoPtr.p);
   return rc_gmdInitFromDict;
}

JNIEXPORT jboolean JNICALL Java_com_gams_api_gmd_InitFromDB(JNIEnv *env, jobject obj, jlong gmdSrcPtr)
{
   int rc_gmdInitFromDB;
   jfieldID fid;
   u64_t pgmd;
   jclass cls = (*env)->GetObjectClass(env, obj);
   u64_t local_gmdSrcPtr;
   fid = (*env)->GetFieldID(env, cls, "gmdPtr", "J");
   if (fid == NULL) return 0;
   pgmd.i = (*env)->GetLongField(env, obj, fid);
   local_gmdSrcPtr.i = gmdSrcPtr;
   rc_gmdInitFromDB = gmdInitFromDB((gmdHandle_t)pgmd.p, local_gmdSrcPtr.p);
   return rc_gmdInitFromDB;
}

JNIEXPORT jboolean JNICALL Java_com_gams_api_gmd_RegisterGMO(JNIEnv *env, jobject obj, jlong gmoPtr)
{
   int rc_gmdRegisterGMO;
   jfieldID fid;
   u64_t pgmd;
   jclass cls = (*env)->GetObjectClass(env, obj);
   u64_t local_gmoPtr;
   fid = (*env)->GetFieldID(env, cls, "gmdPtr", "J");
   if (fid == NULL) return 0;
   pgmd.i = (*env)->GetLongField(env, obj, fid);
   local_gmoPtr.i = gmoPtr;
   rc_gmdRegisterGMO = gmdRegisterGMO((gmdHandle_t)pgmd.p, local_gmoPtr.p);
   return rc_gmdRegisterGMO;
}

JNIEXPORT jboolean JNICALL Java_com_gams_api_gmd_CloseGDX(JNIEnv *env, jobject obj, jboolean loadRemain)
{
   int rc_gmdCloseGDX;
   jfieldID fid;
   u64_t pgmd;
   jclass cls = (*env)->GetObjectClass(env, obj);
   fid = (*env)->GetFieldID(env, cls, "gmdPtr", "J");
   if (fid == NULL) return 0;
   pgmd.i = (*env)->GetLongField(env, obj, fid);
   rc_gmdCloseGDX = gmdCloseGDX((gmdHandle_t)pgmd.p, loadRemain);
   return rc_gmdCloseGDX;
}

JNIEXPORT jboolean JNICALL Java_com_gams_api_gmd_AddSymbolX(JNIEnv *env, jobject obj, jstring symName, jint aDim, jint stype, jint userInfo, jstring explText, jlongArray vDomPtrIn, jobjectArray keyStr, jlongArray symPtr)
{
   int rc_gmdAddSymbolX;
   jfieldID fid;
   u64_t pgmd;
   jclass cls = (*env)->GetObjectClass(env, obj);
   char *local_symName;
   char *local_explText;
   jlong* local_vDomPtrIn;
   void** localCopy_vDomPtrIn;
   int i_keyStr, sidim_keyStr;
   stringUEL local_keyStr[GLOBAL_MAX_INDEX_DIM];
   char *ptr_keyStr[GLOBAL_MAX_INDEX_DIM];
   jlong* local_symPtr;
   void** localCopy_symPtr;
   fid = (*env)->GetFieldID(env, cls, "gmdPtr", "J");
   if (fid == NULL) return 0;
   pgmd.i = (*env)->GetLongField(env, obj, fid);
   local_symName = (char *)(*env)->GetStringUTFChars(env, symName, NULL);
   local_explText = (char *)(*env)->GetStringUTFChars(env, explText, NULL);
   local_vDomPtrIn = (*env)->GetLongArrayElements(env, vDomPtrIn, NULL);
   if( sizeof(jlong) != sizeof(void*) ) {
     jsize localCount;
     u64_t blab;
     localCopy_vDomPtrIn = (void**)malloc(sizeof(void*) * (*env)->GetArrayLength(env, vDomPtrIn));
     for( localCount = 0; localCount < (*env)->GetArrayLength(env, vDomPtrIn); ++localCount ) {
       blab.i = local_vDomPtrIn[localCount];
       localCopy_vDomPtrIn[localCount] = blab.p;
       }
   } else
     localCopy_vDomPtrIn = (void**)local_vDomPtrIn;
   local_symPtr = (*env)->GetLongArrayElements(env, symPtr, NULL);
   if( sizeof(jlong) != sizeof(void*) ) {
     jsize localCount;
     u64_t blab;
     localCopy_symPtr = (void**)malloc(sizeof(void*) * (*env)->GetArrayLength(env, symPtr));
     for( localCount = 0; localCount < (*env)->GetArrayLength(env, symPtr); ++localCount ) {
       blab.i = local_symPtr[localCount];
       localCopy_symPtr[localCount] = blab.p;
       }
   } else
     localCopy_symPtr = (void**)local_symPtr;
   sidim_keyStr = aDim;
   for(i_keyStr=0;i_keyStr<sidim_keyStr;++i_keyStr) {
      jstring js_;
      char *str_;
      ptr_keyStr[i_keyStr] = local_keyStr[i_keyStr];
      js_ = (*env)->GetObjectArrayElement(env, keyStr, i_keyStr);
      if (js_==NULL)
          js_ = (*env)->NewStringUTF(env, "");
      str_ = (char*) (*env)->GetStringUTFChars(env, js_, NULL);
      strncpy(local_keyStr[i_keyStr], str_, GLOBAL_UEL_IDENT_SIZE-1);
      local_keyStr[i_keyStr][GLOBAL_UEL_IDENT_SIZE-1] = '\0';
      (*env)->ReleaseStringUTFChars(env, js_, str_);
   }
   rc_gmdAddSymbolX = gmdAddSymbolX((gmdHandle_t)pgmd.p, local_symName, aDim, stype, userInfo, local_explText, localCopy_vDomPtrIn, ptr_keyStr, localCopy_symPtr);
   (*env)->ReleaseStringUTFChars(env, symName, local_symName);
   (*env)->ReleaseStringUTFChars(env, explText, local_explText);
   (*env)->ReleaseLongArrayElements(env, vDomPtrIn, local_vDomPtrIn, 0);
   if( sizeof(jlong) != sizeof(void*) ) {
     jsize localCount;
     u64_t blub;
     for( localCount = 0; localCount < (*env)->GetArrayLength(env, vDomPtrIn); ++localCount ) {
       blub.i = 0; blub.p = localCopy_vDomPtrIn[localCount];
       (*env)->SetLongArrayRegion(env, vDomPtrIn, localCount, 1, &blub.i);
     }
     free(localCopy_vDomPtrIn);
   }
   (*env)->ReleaseLongArrayElements(env, symPtr, local_symPtr, 0);
   if( sizeof(jlong) != sizeof(void*) ) {
     jsize localCount;
     u64_t blub;
     for( localCount = 0; localCount < (*env)->GetArrayLength(env, symPtr); ++localCount ) {
       blub.i = 0; blub.p = localCopy_symPtr[localCount];
       (*env)->SetLongArrayRegion(env, symPtr, localCount, 1, &blub.i);
     }
     free(localCopy_symPtr);
   }
   return rc_gmdAddSymbolX;
}

JNIEXPORT jlong JNICALL Java_com_gams_api_gmd_AddSymbolXPy(JNIEnv *env, jobject obj, jstring symName, jint aDim, jint stype, jint userInfo, jstring explText, jlongArray vDomPtrIn, jobjectArray keyStr, jbooleanArray status)
{
   u64_t rc_gmdAddSymbolXPy;
   jfieldID fid;
   u64_t pgmd;
   jclass cls = (*env)->GetObjectClass(env, obj);
   char *local_symName;
   char *local_explText;
   jlong* local_vDomPtrIn;
   void** localCopy_vDomPtrIn;
   int i_keyStr, sidim_keyStr;
   stringUEL local_keyStr[GLOBAL_MAX_INDEX_DIM];
   char *ptr_keyStr[GLOBAL_MAX_INDEX_DIM];
   jboolean *local_status;
   int ib_status = 0;
   fid = (*env)->GetFieldID(env, cls, "gmdPtr", "J");
   if (fid == NULL) return (jlong) NULL;
   pgmd.i = (*env)->GetLongField(env, obj, fid);
   local_symName = (char *)(*env)->GetStringUTFChars(env, symName, NULL);
   local_explText = (char *)(*env)->GetStringUTFChars(env, explText, NULL);
   local_vDomPtrIn = (*env)->GetLongArrayElements(env, vDomPtrIn, NULL);
   if( sizeof(jlong) != sizeof(void*) ) {
     jsize localCount;
     u64_t blab;
     localCopy_vDomPtrIn = (void**)malloc(sizeof(void*) * (*env)->GetArrayLength(env, vDomPtrIn));
     for( localCount = 0; localCount < (*env)->GetArrayLength(env, vDomPtrIn); ++localCount ) {
       blab.i = local_vDomPtrIn[localCount];
       localCopy_vDomPtrIn[localCount] = blab.p;
       }
   } else
     localCopy_vDomPtrIn = (void**)local_vDomPtrIn;
   local_status = (*env)->GetBooleanArrayElements(env, status, NULL);
   if(local_status[0]) ib_status = 1;
   sidim_keyStr = aDim;
   for(i_keyStr=0;i_keyStr<sidim_keyStr;++i_keyStr) {
      jstring js_;
      char *str_;
      ptr_keyStr[i_keyStr] = local_keyStr[i_keyStr];
      js_ = (*env)->GetObjectArrayElement(env, keyStr, i_keyStr);
      if (js_==NULL)
          js_ = (*env)->NewStringUTF(env, "");
      str_ = (char*) (*env)->GetStringUTFChars(env, js_, NULL);
      strncpy(local_keyStr[i_keyStr], str_, GLOBAL_UEL_IDENT_SIZE-1);
      local_keyStr[i_keyStr][GLOBAL_UEL_IDENT_SIZE-1] = '\0';
      (*env)->ReleaseStringUTFChars(env, js_, str_);
   }
   rc_gmdAddSymbolXPy.p = gmdAddSymbolXPy((gmdHandle_t)pgmd.p, local_symName, aDim, stype, userInfo, local_explText, localCopy_vDomPtrIn, ptr_keyStr, &ib_status);
   (*env)->ReleaseStringUTFChars(env, symName, local_symName);
   (*env)->ReleaseStringUTFChars(env, explText, local_explText);
   (*env)->ReleaseLongArrayElements(env, vDomPtrIn, local_vDomPtrIn, 0);
   if( sizeof(jlong) != sizeof(void*) ) {
     jsize localCount;
     u64_t blub;
     for( localCount = 0; localCount < (*env)->GetArrayLength(env, vDomPtrIn); ++localCount ) {
       blub.i = 0; blub.p = localCopy_vDomPtrIn[localCount];
       (*env)->SetLongArrayRegion(env, vDomPtrIn, localCount, 1, &blub.i);
     }
     free(localCopy_vDomPtrIn);
   }
   if(ib_status) local_status[0] = JNI_TRUE; else local_status[0] = JNI_FALSE;
   (*env)->ReleaseBooleanArrayElements(env, status, local_status, 0);
   return rc_gmdAddSymbolXPy.i;
}

JNIEXPORT jboolean JNICALL Java_com_gams_api_gmd_AddSymbol(JNIEnv *env, jobject obj, jstring symName, jint aDim, jint stype, jint userInfo, jstring explText, jlongArray symPtr)
{
   int rc_gmdAddSymbol;
   jfieldID fid;
   u64_t pgmd;
   jclass cls = (*env)->GetObjectClass(env, obj);
   char *local_symName;
   char *local_explText;
   jlong* local_symPtr;
   void** localCopy_symPtr;
   fid = (*env)->GetFieldID(env, cls, "gmdPtr", "J");
   if (fid == NULL) return 0;
   pgmd.i = (*env)->GetLongField(env, obj, fid);
   local_symName = (char *)(*env)->GetStringUTFChars(env, symName, NULL);
   local_explText = (char *)(*env)->GetStringUTFChars(env, explText, NULL);
   local_symPtr = (*env)->GetLongArrayElements(env, symPtr, NULL);
   if( sizeof(jlong) != sizeof(void*) ) {
     jsize localCount;
     u64_t blab;
     localCopy_symPtr = (void**)malloc(sizeof(void*) * (*env)->GetArrayLength(env, symPtr));
     for( localCount = 0; localCount < (*env)->GetArrayLength(env, symPtr); ++localCount ) {
       blab.i = local_symPtr[localCount];
       localCopy_symPtr[localCount] = blab.p;
       }
   } else
     localCopy_symPtr = (void**)local_symPtr;
   rc_gmdAddSymbol = gmdAddSymbol((gmdHandle_t)pgmd.p, local_symName, aDim, stype, userInfo, local_explText, localCopy_symPtr);
   (*env)->ReleaseStringUTFChars(env, symName, local_symName);
   (*env)->ReleaseStringUTFChars(env, explText, local_explText);
   (*env)->ReleaseLongArrayElements(env, symPtr, local_symPtr, 0);
   if( sizeof(jlong) != sizeof(void*) ) {
     jsize localCount;
     u64_t blub;
     for( localCount = 0; localCount < (*env)->GetArrayLength(env, symPtr); ++localCount ) {
       blub.i = 0; blub.p = localCopy_symPtr[localCount];
       (*env)->SetLongArrayRegion(env, symPtr, localCount, 1, &blub.i);
     }
     free(localCopy_symPtr);
   }
   return rc_gmdAddSymbol;
}

JNIEXPORT jlong JNICALL Java_com_gams_api_gmd_AddSymbolPy(JNIEnv *env, jobject obj, jstring symName, jint aDim, jint stype, jint userInfo, jstring explText, jbooleanArray status)
{
   u64_t rc_gmdAddSymbolPy;
   jfieldID fid;
   u64_t pgmd;
   jclass cls = (*env)->GetObjectClass(env, obj);
   char *local_symName;
   char *local_explText;
   jboolean *local_status;
   int ib_status = 0;
   fid = (*env)->GetFieldID(env, cls, "gmdPtr", "J");
   if (fid == NULL) return (jlong) NULL;
   pgmd.i = (*env)->GetLongField(env, obj, fid);
   local_symName = (char *)(*env)->GetStringUTFChars(env, symName, NULL);
   local_explText = (char *)(*env)->GetStringUTFChars(env, explText, NULL);
   local_status = (*env)->GetBooleanArrayElements(env, status, NULL);
   if(local_status[0]) ib_status = 1;
   rc_gmdAddSymbolPy.p = gmdAddSymbolPy((gmdHandle_t)pgmd.p, local_symName, aDim, stype, userInfo, local_explText, &ib_status);
   (*env)->ReleaseStringUTFChars(env, symName, local_symName);
   (*env)->ReleaseStringUTFChars(env, explText, local_explText);
   if(ib_status) local_status[0] = JNI_TRUE; else local_status[0] = JNI_FALSE;
   (*env)->ReleaseBooleanArrayElements(env, status, local_status, 0);
   return rc_gmdAddSymbolPy.i;
}

JNIEXPORT jboolean JNICALL Java_com_gams_api_gmd_FindSymbol(JNIEnv *env, jobject obj, jstring symName, jlongArray symPtr)
{
   int rc_gmdFindSymbol;
   jfieldID fid;
   u64_t pgmd;
   jclass cls = (*env)->GetObjectClass(env, obj);
   char *local_symName;
   jlong* local_symPtr;
   void** localCopy_symPtr;
   fid = (*env)->GetFieldID(env, cls, "gmdPtr", "J");
   if (fid == NULL) return 0;
   pgmd.i = (*env)->GetLongField(env, obj, fid);
   local_symName = (char *)(*env)->GetStringUTFChars(env, symName, NULL);
   local_symPtr = (*env)->GetLongArrayElements(env, symPtr, NULL);
   if( sizeof(jlong) != sizeof(void*) ) {
     jsize localCount;
     u64_t blab;
     localCopy_symPtr = (void**)malloc(sizeof(void*) * (*env)->GetArrayLength(env, symPtr));
     for( localCount = 0; localCount < (*env)->GetArrayLength(env, symPtr); ++localCount ) {
       blab.i = local_symPtr[localCount];
       localCopy_symPtr[localCount] = blab.p;
       }
   } else
     localCopy_symPtr = (void**)local_symPtr;
   rc_gmdFindSymbol = gmdFindSymbol((gmdHandle_t)pgmd.p, local_symName, localCopy_symPtr);
   (*env)->ReleaseStringUTFChars(env, symName, local_symName);
   (*env)->ReleaseLongArrayElements(env, symPtr, local_symPtr, 0);
   if( sizeof(jlong) != sizeof(void*) ) {
     jsize localCount;
     u64_t blub;
     for( localCount = 0; localCount < (*env)->GetArrayLength(env, symPtr); ++localCount ) {
       blub.i = 0; blub.p = localCopy_symPtr[localCount];
       (*env)->SetLongArrayRegion(env, symPtr, localCount, 1, &blub.i);
     }
     free(localCopy_symPtr);
   }
   return rc_gmdFindSymbol;
}

JNIEXPORT jlong JNICALL Java_com_gams_api_gmd_FindSymbolPy(JNIEnv *env, jobject obj, jstring symName, jbooleanArray status)
{
   u64_t rc_gmdFindSymbolPy;
   jfieldID fid;
   u64_t pgmd;
   jclass cls = (*env)->GetObjectClass(env, obj);
   char *local_symName;
   jboolean *local_status;
   int ib_status = 0;
   fid = (*env)->GetFieldID(env, cls, "gmdPtr", "J");
   if (fid == NULL) return (jlong) NULL;
   pgmd.i = (*env)->GetLongField(env, obj, fid);
   local_symName = (char *)(*env)->GetStringUTFChars(env, symName, NULL);
   local_status = (*env)->GetBooleanArrayElements(env, status, NULL);
   if(local_status[0]) ib_status = 1;
   rc_gmdFindSymbolPy.p = gmdFindSymbolPy((gmdHandle_t)pgmd.p, local_symName, &ib_status);
   (*env)->ReleaseStringUTFChars(env, symName, local_symName);
   if(ib_status) local_status[0] = JNI_TRUE; else local_status[0] = JNI_FALSE;
   (*env)->ReleaseBooleanArrayElements(env, status, local_status, 0);
   return rc_gmdFindSymbolPy.i;
}

JNIEXPORT jboolean JNICALL Java_com_gams_api_gmd_GetSymbolByIndex(JNIEnv *env, jobject obj, jint idx, jlongArray symPtr)
{
   int rc_gmdGetSymbolByIndex;
   jfieldID fid;
   u64_t pgmd;
   jclass cls = (*env)->GetObjectClass(env, obj);
   jlong* local_symPtr;
   void** localCopy_symPtr;
   fid = (*env)->GetFieldID(env, cls, "gmdPtr", "J");
   if (fid == NULL) return 0;
   pgmd.i = (*env)->GetLongField(env, obj, fid);
   local_symPtr = (*env)->GetLongArrayElements(env, symPtr, NULL);
   if( sizeof(jlong) != sizeof(void*) ) {
     jsize localCount;
     u64_t blab;
     localCopy_symPtr = (void**)malloc(sizeof(void*) * (*env)->GetArrayLength(env, symPtr));
     for( localCount = 0; localCount < (*env)->GetArrayLength(env, symPtr); ++localCount ) {
       blab.i = local_symPtr[localCount];
       localCopy_symPtr[localCount] = blab.p;
       }
   } else
     localCopy_symPtr = (void**)local_symPtr;
   rc_gmdGetSymbolByIndex = gmdGetSymbolByIndex((gmdHandle_t)pgmd.p, idx, localCopy_symPtr);
   (*env)->ReleaseLongArrayElements(env, symPtr, local_symPtr, 0);
   if( sizeof(jlong) != sizeof(void*) ) {
     jsize localCount;
     u64_t blub;
     for( localCount = 0; localCount < (*env)->GetArrayLength(env, symPtr); ++localCount ) {
       blub.i = 0; blub.p = localCopy_symPtr[localCount];
       (*env)->SetLongArrayRegion(env, symPtr, localCount, 1, &blub.i);
     }
     free(localCopy_symPtr);
   }
   return rc_gmdGetSymbolByIndex;
}

JNIEXPORT jlong JNICALL Java_com_gams_api_gmd_GetSymbolByIndexPy(JNIEnv *env, jobject obj, jint idx, jbooleanArray status)
{
   u64_t rc_gmdGetSymbolByIndexPy;
   jfieldID fid;
   u64_t pgmd;
   jclass cls = (*env)->GetObjectClass(env, obj);
   jboolean *local_status;
   int ib_status = 0;
   fid = (*env)->GetFieldID(env, cls, "gmdPtr", "J");
   if (fid == NULL) return (jlong) NULL;
   pgmd.i = (*env)->GetLongField(env, obj, fid);
   local_status = (*env)->GetBooleanArrayElements(env, status, NULL);
   if(local_status[0]) ib_status = 1;
   rc_gmdGetSymbolByIndexPy.p = gmdGetSymbolByIndexPy((gmdHandle_t)pgmd.p, idx, &ib_status);
   if(ib_status) local_status[0] = JNI_TRUE; else local_status[0] = JNI_FALSE;
   (*env)->ReleaseBooleanArrayElements(env, status, local_status, 0);
   return rc_gmdGetSymbolByIndexPy.i;
}

JNIEXPORT jboolean JNICALL Java_com_gams_api_gmd_ClearSymbol(JNIEnv *env, jobject obj, jlong symPtr)
{
   int rc_gmdClearSymbol;
   jfieldID fid;
   u64_t pgmd;
   jclass cls = (*env)->GetObjectClass(env, obj);
   u64_t local_symPtr;
   fid = (*env)->GetFieldID(env, cls, "gmdPtr", "J");
   if (fid == NULL) return 0;
   pgmd.i = (*env)->GetLongField(env, obj, fid);
   local_symPtr.i = symPtr;
   rc_gmdClearSymbol = gmdClearSymbol((gmdHandle_t)pgmd.p, local_symPtr.p);
   return rc_gmdClearSymbol;
}

JNIEXPORT jboolean JNICALL Java_com_gams_api_gmd_CopySymbol(JNIEnv *env, jobject obj, jlong tarSymPtr, jlong srcSymPtr)
{
   int rc_gmdCopySymbol;
   jfieldID fid;
   u64_t pgmd;
   jclass cls = (*env)->GetObjectClass(env, obj);
   u64_t local_tarSymPtr;
   u64_t local_srcSymPtr;
   fid = (*env)->GetFieldID(env, cls, "gmdPtr", "J");
   if (fid == NULL) return 0;
   pgmd.i = (*env)->GetLongField(env, obj, fid);
   local_tarSymPtr.i = tarSymPtr;
   local_srcSymPtr.i = srcSymPtr;
   rc_gmdCopySymbol = gmdCopySymbol((gmdHandle_t)pgmd.p, local_tarSymPtr.p, local_srcSymPtr.p);
   return rc_gmdCopySymbol;
}

JNIEXPORT jboolean JNICALL Java_com_gams_api_gmd_FindRecord(JNIEnv *env, jobject obj, jlong symPtr, jobjectArray keyStr, jlongArray symIterPtr)
{
   int rc_gmdFindRecord;
   jfieldID fid;
   u64_t pgmd;
   jclass cls = (*env)->GetObjectClass(env, obj);
   u64_t local_symPtr;
   int i_keyStr, sidim_keyStr;
   stringUEL local_keyStr[GLOBAL_MAX_INDEX_DIM];
   char *ptr_keyStr[GLOBAL_MAX_INDEX_DIM];
   jlong* local_symIterPtr;
   void** localCopy_symIterPtr;
   fid = (*env)->GetFieldID(env, cls, "gmdPtr", "J");
   if (fid == NULL) return 0;
   pgmd.i = (*env)->GetLongField(env, obj, fid);
   local_symPtr.i = symPtr;
   local_symIterPtr = (*env)->GetLongArrayElements(env, symIterPtr, NULL);
   if( sizeof(jlong) != sizeof(void*) ) {
     jsize localCount;
     u64_t blab;
     localCopy_symIterPtr = (void**)malloc(sizeof(void*) * (*env)->GetArrayLength(env, symIterPtr));
     for( localCount = 0; localCount < (*env)->GetArrayLength(env, symIterPtr); ++localCount ) {
       blab.i = local_symIterPtr[localCount];
       localCopy_symIterPtr[localCount] = blab.p;
       }
   } else
     localCopy_symIterPtr = (void**)local_symIterPtr;
   if(!gmdSymbolDim((gmdHandle_t)pgmd.p, local_symPtr.p, &sidim_keyStr)) return 0;
   for(i_keyStr=0;i_keyStr<sidim_keyStr;++i_keyStr) {
      jstring js_;
      char *str_;
      ptr_keyStr[i_keyStr] = local_keyStr[i_keyStr];
      js_ = (*env)->GetObjectArrayElement(env, keyStr, i_keyStr);
      if (js_==NULL)
          js_ = (*env)->NewStringUTF(env, "");
      str_ = (char*) (*env)->GetStringUTFChars(env, js_, NULL);
      strncpy(local_keyStr[i_keyStr], str_, GLOBAL_UEL_IDENT_SIZE-1);
      local_keyStr[i_keyStr][GLOBAL_UEL_IDENT_SIZE-1] = '\0';
      (*env)->ReleaseStringUTFChars(env, js_, str_);
   }
   rc_gmdFindRecord = gmdFindRecord((gmdHandle_t)pgmd.p, local_symPtr.p, ptr_keyStr, localCopy_symIterPtr);
   (*env)->ReleaseLongArrayElements(env, symIterPtr, local_symIterPtr, 0);
   if( sizeof(jlong) != sizeof(void*) ) {
     jsize localCount;
     u64_t blub;
     for( localCount = 0; localCount < (*env)->GetArrayLength(env, symIterPtr); ++localCount ) {
       blub.i = 0; blub.p = localCopy_symIterPtr[localCount];
       (*env)->SetLongArrayRegion(env, symIterPtr, localCount, 1, &blub.i);
     }
     free(localCopy_symIterPtr);
   }
   return rc_gmdFindRecord;
}

JNIEXPORT jlong JNICALL Java_com_gams_api_gmd_FindRecordPy(JNIEnv *env, jobject obj, jlong symPtr, jobjectArray keyStr, jbooleanArray status)
{
   u64_t rc_gmdFindRecordPy;
   jfieldID fid;
   u64_t pgmd;
   jclass cls = (*env)->GetObjectClass(env, obj);
   u64_t local_symPtr;
   int i_keyStr, sidim_keyStr;
   stringUEL local_keyStr[GLOBAL_MAX_INDEX_DIM];
   char *ptr_keyStr[GLOBAL_MAX_INDEX_DIM];
   jboolean *local_status;
   int ib_status = 0;
   fid = (*env)->GetFieldID(env, cls, "gmdPtr", "J");
   if (fid == NULL) return (jlong) NULL;
   pgmd.i = (*env)->GetLongField(env, obj, fid);
   local_symPtr.i = symPtr;
   local_status = (*env)->GetBooleanArrayElements(env, status, NULL);
   if(local_status[0]) ib_status = 1;
   if(!gmdSymbolDim((gmdHandle_t)pgmd.p, local_symPtr.p, &sidim_keyStr)) return 0;
   for(i_keyStr=0;i_keyStr<sidim_keyStr;++i_keyStr) {
      jstring js_;
      char *str_;
      ptr_keyStr[i_keyStr] = local_keyStr[i_keyStr];
      js_ = (*env)->GetObjectArrayElement(env, keyStr, i_keyStr);
      if (js_==NULL)
          js_ = (*env)->NewStringUTF(env, "");
      str_ = (char*) (*env)->GetStringUTFChars(env, js_, NULL);
      strncpy(local_keyStr[i_keyStr], str_, GLOBAL_UEL_IDENT_SIZE-1);
      local_keyStr[i_keyStr][GLOBAL_UEL_IDENT_SIZE-1] = '\0';
      (*env)->ReleaseStringUTFChars(env, js_, str_);
   }
   rc_gmdFindRecordPy.p = gmdFindRecordPy((gmdHandle_t)pgmd.p, local_symPtr.p, ptr_keyStr, &ib_status);
   if(ib_status) local_status[0] = JNI_TRUE; else local_status[0] = JNI_FALSE;
   (*env)->ReleaseBooleanArrayElements(env, status, local_status, 0);
   return rc_gmdFindRecordPy.i;
}

JNIEXPORT jboolean JNICALL Java_com_gams_api_gmd_FindFirstRecord(JNIEnv *env, jobject obj, jlong symPtr, jlongArray symIterPtr)
{
   int rc_gmdFindFirstRecord;
   jfieldID fid;
   u64_t pgmd;
   jclass cls = (*env)->GetObjectClass(env, obj);
   u64_t local_symPtr;
   jlong* local_symIterPtr;
   void** localCopy_symIterPtr;
   fid = (*env)->GetFieldID(env, cls, "gmdPtr", "J");
   if (fid == NULL) return 0;
   pgmd.i = (*env)->GetLongField(env, obj, fid);
   local_symPtr.i = symPtr;
   local_symIterPtr = (*env)->GetLongArrayElements(env, symIterPtr, NULL);
   if( sizeof(jlong) != sizeof(void*) ) {
     jsize localCount;
     u64_t blab;
     localCopy_symIterPtr = (void**)malloc(sizeof(void*) * (*env)->GetArrayLength(env, symIterPtr));
     for( localCount = 0; localCount < (*env)->GetArrayLength(env, symIterPtr); ++localCount ) {
       blab.i = local_symIterPtr[localCount];
       localCopy_symIterPtr[localCount] = blab.p;
       }
   } else
     localCopy_symIterPtr = (void**)local_symIterPtr;
   rc_gmdFindFirstRecord = gmdFindFirstRecord((gmdHandle_t)pgmd.p, local_symPtr.p, localCopy_symIterPtr);
   (*env)->ReleaseLongArrayElements(env, symIterPtr, local_symIterPtr, 0);
   if( sizeof(jlong) != sizeof(void*) ) {
     jsize localCount;
     u64_t blub;
     for( localCount = 0; localCount < (*env)->GetArrayLength(env, symIterPtr); ++localCount ) {
       blub.i = 0; blub.p = localCopy_symIterPtr[localCount];
       (*env)->SetLongArrayRegion(env, symIterPtr, localCount, 1, &blub.i);
     }
     free(localCopy_symIterPtr);
   }
   return rc_gmdFindFirstRecord;
}

JNIEXPORT jlong JNICALL Java_com_gams_api_gmd_FindFirstRecordPy(JNIEnv *env, jobject obj, jlong symPtr, jbooleanArray status)
{
   u64_t rc_gmdFindFirstRecordPy;
   jfieldID fid;
   u64_t pgmd;
   jclass cls = (*env)->GetObjectClass(env, obj);
   u64_t local_symPtr;
   jboolean *local_status;
   int ib_status = 0;
   fid = (*env)->GetFieldID(env, cls, "gmdPtr", "J");
   if (fid == NULL) return (jlong) NULL;
   pgmd.i = (*env)->GetLongField(env, obj, fid);
   local_symPtr.i = symPtr;
   local_status = (*env)->GetBooleanArrayElements(env, status, NULL);
   if(local_status[0]) ib_status = 1;
   rc_gmdFindFirstRecordPy.p = gmdFindFirstRecordPy((gmdHandle_t)pgmd.p, local_symPtr.p, &ib_status);
   if(ib_status) local_status[0] = JNI_TRUE; else local_status[0] = JNI_FALSE;
   (*env)->ReleaseBooleanArrayElements(env, status, local_status, 0);
   return rc_gmdFindFirstRecordPy.i;
}

JNIEXPORT jboolean JNICALL Java_com_gams_api_gmd_FindFirstRecordSlice(JNIEnv *env, jobject obj, jlong symPtr, jobjectArray keyStr, jlongArray symIterPtr)
{
   int rc_gmdFindFirstRecordSlice;
   jfieldID fid;
   u64_t pgmd;
   jclass cls = (*env)->GetObjectClass(env, obj);
   u64_t local_symPtr;
   int i_keyStr, sidim_keyStr;
   stringUEL local_keyStr[GLOBAL_MAX_INDEX_DIM];
   char *ptr_keyStr[GLOBAL_MAX_INDEX_DIM];
   jlong* local_symIterPtr;
   void** localCopy_symIterPtr;
   fid = (*env)->GetFieldID(env, cls, "gmdPtr", "J");
   if (fid == NULL) return 0;
   pgmd.i = (*env)->GetLongField(env, obj, fid);
   local_symPtr.i = symPtr;
   local_symIterPtr = (*env)->GetLongArrayElements(env, symIterPtr, NULL);
   if( sizeof(jlong) != sizeof(void*) ) {
     jsize localCount;
     u64_t blab;
     localCopy_symIterPtr = (void**)malloc(sizeof(void*) * (*env)->GetArrayLength(env, symIterPtr));
     for( localCount = 0; localCount < (*env)->GetArrayLength(env, symIterPtr); ++localCount ) {
       blab.i = local_symIterPtr[localCount];
       localCopy_symIterPtr[localCount] = blab.p;
       }
   } else
     localCopy_symIterPtr = (void**)local_symIterPtr;
   if(!gmdSymbolDim((gmdHandle_t)pgmd.p, local_symPtr.p, &sidim_keyStr)) return 0;
   for(i_keyStr=0;i_keyStr<sidim_keyStr;++i_keyStr) {
      jstring js_;
      char *str_;
      ptr_keyStr[i_keyStr] = local_keyStr[i_keyStr];
      js_ = (*env)->GetObjectArrayElement(env, keyStr, i_keyStr);
      if (js_==NULL)
          js_ = (*env)->NewStringUTF(env, "");
      str_ = (char*) (*env)->GetStringUTFChars(env, js_, NULL);
      strncpy(local_keyStr[i_keyStr], str_, GLOBAL_UEL_IDENT_SIZE-1);
      local_keyStr[i_keyStr][GLOBAL_UEL_IDENT_SIZE-1] = '\0';
      (*env)->ReleaseStringUTFChars(env, js_, str_);
   }
   rc_gmdFindFirstRecordSlice = gmdFindFirstRecordSlice((gmdHandle_t)pgmd.p, local_symPtr.p, ptr_keyStr, localCopy_symIterPtr);
   (*env)->ReleaseLongArrayElements(env, symIterPtr, local_symIterPtr, 0);
   if( sizeof(jlong) != sizeof(void*) ) {
     jsize localCount;
     u64_t blub;
     for( localCount = 0; localCount < (*env)->GetArrayLength(env, symIterPtr); ++localCount ) {
       blub.i = 0; blub.p = localCopy_symIterPtr[localCount];
       (*env)->SetLongArrayRegion(env, symIterPtr, localCount, 1, &blub.i);
     }
     free(localCopy_symIterPtr);
   }
   return rc_gmdFindFirstRecordSlice;
}

JNIEXPORT jlong JNICALL Java_com_gams_api_gmd_FindFirstRecordSlicePy(JNIEnv *env, jobject obj, jlong symPtr, jobjectArray keyStr, jbooleanArray status)
{
   u64_t rc_gmdFindFirstRecordSlicePy;
   jfieldID fid;
   u64_t pgmd;
   jclass cls = (*env)->GetObjectClass(env, obj);
   u64_t local_symPtr;
   int i_keyStr, sidim_keyStr;
   stringUEL local_keyStr[GLOBAL_MAX_INDEX_DIM];
   char *ptr_keyStr[GLOBAL_MAX_INDEX_DIM];
   jboolean *local_status;
   int ib_status = 0;
   fid = (*env)->GetFieldID(env, cls, "gmdPtr", "J");
   if (fid == NULL) return (jlong) NULL;
   pgmd.i = (*env)->GetLongField(env, obj, fid);
   local_symPtr.i = symPtr;
   local_status = (*env)->GetBooleanArrayElements(env, status, NULL);
   if(local_status[0]) ib_status = 1;
   if(!gmdSymbolDim((gmdHandle_t)pgmd.p, local_symPtr.p, &sidim_keyStr)) return 0;
   for(i_keyStr=0;i_keyStr<sidim_keyStr;++i_keyStr) {
      jstring js_;
      char *str_;
      ptr_keyStr[i_keyStr] = local_keyStr[i_keyStr];
      js_ = (*env)->GetObjectArrayElement(env, keyStr, i_keyStr);
      if (js_==NULL)
          js_ = (*env)->NewStringUTF(env, "");
      str_ = (char*) (*env)->GetStringUTFChars(env, js_, NULL);
      strncpy(local_keyStr[i_keyStr], str_, GLOBAL_UEL_IDENT_SIZE-1);
      local_keyStr[i_keyStr][GLOBAL_UEL_IDENT_SIZE-1] = '\0';
      (*env)->ReleaseStringUTFChars(env, js_, str_);
   }
   rc_gmdFindFirstRecordSlicePy.p = gmdFindFirstRecordSlicePy((gmdHandle_t)pgmd.p, local_symPtr.p, ptr_keyStr, &ib_status);
   if(ib_status) local_status[0] = JNI_TRUE; else local_status[0] = JNI_FALSE;
   (*env)->ReleaseBooleanArrayElements(env, status, local_status, 0);
   return rc_gmdFindFirstRecordSlicePy.i;
}

JNIEXPORT jboolean JNICALL Java_com_gams_api_gmd_FindLastRecord(JNIEnv *env, jobject obj, jlong symPtr, jlongArray symIterPtr)
{
   int rc_gmdFindLastRecord;
   jfieldID fid;
   u64_t pgmd;
   jclass cls = (*env)->GetObjectClass(env, obj);
   u64_t local_symPtr;
   jlong* local_symIterPtr;
   void** localCopy_symIterPtr;
   fid = (*env)->GetFieldID(env, cls, "gmdPtr", "J");
   if (fid == NULL) return 0;
   pgmd.i = (*env)->GetLongField(env, obj, fid);
   local_symPtr.i = symPtr;
   local_symIterPtr = (*env)->GetLongArrayElements(env, symIterPtr, NULL);
   if( sizeof(jlong) != sizeof(void*) ) {
     jsize localCount;
     u64_t blab;
     localCopy_symIterPtr = (void**)malloc(sizeof(void*) * (*env)->GetArrayLength(env, symIterPtr));
     for( localCount = 0; localCount < (*env)->GetArrayLength(env, symIterPtr); ++localCount ) {
       blab.i = local_symIterPtr[localCount];
       localCopy_symIterPtr[localCount] = blab.p;
       }
   } else
     localCopy_symIterPtr = (void**)local_symIterPtr;
   rc_gmdFindLastRecord = gmdFindLastRecord((gmdHandle_t)pgmd.p, local_symPtr.p, localCopy_symIterPtr);
   (*env)->ReleaseLongArrayElements(env, symIterPtr, local_symIterPtr, 0);
   if( sizeof(jlong) != sizeof(void*) ) {
     jsize localCount;
     u64_t blub;
     for( localCount = 0; localCount < (*env)->GetArrayLength(env, symIterPtr); ++localCount ) {
       blub.i = 0; blub.p = localCopy_symIterPtr[localCount];
       (*env)->SetLongArrayRegion(env, symIterPtr, localCount, 1, &blub.i);
     }
     free(localCopy_symIterPtr);
   }
   return rc_gmdFindLastRecord;
}

JNIEXPORT jlong JNICALL Java_com_gams_api_gmd_FindLastRecordPy(JNIEnv *env, jobject obj, jlong symPtr, jbooleanArray status)
{
   u64_t rc_gmdFindLastRecordPy;
   jfieldID fid;
   u64_t pgmd;
   jclass cls = (*env)->GetObjectClass(env, obj);
   u64_t local_symPtr;
   jboolean *local_status;
   int ib_status = 0;
   fid = (*env)->GetFieldID(env, cls, "gmdPtr", "J");
   if (fid == NULL) return (jlong) NULL;
   pgmd.i = (*env)->GetLongField(env, obj, fid);
   local_symPtr.i = symPtr;
   local_status = (*env)->GetBooleanArrayElements(env, status, NULL);
   if(local_status[0]) ib_status = 1;
   rc_gmdFindLastRecordPy.p = gmdFindLastRecordPy((gmdHandle_t)pgmd.p, local_symPtr.p, &ib_status);
   if(ib_status) local_status[0] = JNI_TRUE; else local_status[0] = JNI_FALSE;
   (*env)->ReleaseBooleanArrayElements(env, status, local_status, 0);
   return rc_gmdFindLastRecordPy.i;
}

JNIEXPORT jboolean JNICALL Java_com_gams_api_gmd_FindLastRecordSlice(JNIEnv *env, jobject obj, jlong symPtr, jobjectArray keyStr, jlongArray symIterPtr)
{
   int rc_gmdFindLastRecordSlice;
   jfieldID fid;
   u64_t pgmd;
   jclass cls = (*env)->GetObjectClass(env, obj);
   u64_t local_symPtr;
   int i_keyStr, sidim_keyStr;
   stringUEL local_keyStr[GLOBAL_MAX_INDEX_DIM];
   char *ptr_keyStr[GLOBAL_MAX_INDEX_DIM];
   jlong* local_symIterPtr;
   void** localCopy_symIterPtr;
   fid = (*env)->GetFieldID(env, cls, "gmdPtr", "J");
   if (fid == NULL) return 0;
   pgmd.i = (*env)->GetLongField(env, obj, fid);
   local_symPtr.i = symPtr;
   local_symIterPtr = (*env)->GetLongArrayElements(env, symIterPtr, NULL);
   if( sizeof(jlong) != sizeof(void*) ) {
     jsize localCount;
     u64_t blab;
     localCopy_symIterPtr = (void**)malloc(sizeof(void*) * (*env)->GetArrayLength(env, symIterPtr));
     for( localCount = 0; localCount < (*env)->GetArrayLength(env, symIterPtr); ++localCount ) {
       blab.i = local_symIterPtr[localCount];
       localCopy_symIterPtr[localCount] = blab.p;
       }
   } else
     localCopy_symIterPtr = (void**)local_symIterPtr;
   if(!gmdSymbolDim((gmdHandle_t)pgmd.p, local_symPtr.p, &sidim_keyStr)) return 0;
   for(i_keyStr=0;i_keyStr<sidim_keyStr;++i_keyStr) {
      jstring js_;
      char *str_;
      ptr_keyStr[i_keyStr] = local_keyStr[i_keyStr];
      js_ = (*env)->GetObjectArrayElement(env, keyStr, i_keyStr);
      if (js_==NULL)
          js_ = (*env)->NewStringUTF(env, "");
      str_ = (char*) (*env)->GetStringUTFChars(env, js_, NULL);
      strncpy(local_keyStr[i_keyStr], str_, GLOBAL_UEL_IDENT_SIZE-1);
      local_keyStr[i_keyStr][GLOBAL_UEL_IDENT_SIZE-1] = '\0';
      (*env)->ReleaseStringUTFChars(env, js_, str_);
   }
   rc_gmdFindLastRecordSlice = gmdFindLastRecordSlice((gmdHandle_t)pgmd.p, local_symPtr.p, ptr_keyStr, localCopy_symIterPtr);
   (*env)->ReleaseLongArrayElements(env, symIterPtr, local_symIterPtr, 0);
   if( sizeof(jlong) != sizeof(void*) ) {
     jsize localCount;
     u64_t blub;
     for( localCount = 0; localCount < (*env)->GetArrayLength(env, symIterPtr); ++localCount ) {
       blub.i = 0; blub.p = localCopy_symIterPtr[localCount];
       (*env)->SetLongArrayRegion(env, symIterPtr, localCount, 1, &blub.i);
     }
     free(localCopy_symIterPtr);
   }
   return rc_gmdFindLastRecordSlice;
}

JNIEXPORT jlong JNICALL Java_com_gams_api_gmd_FindLastRecordSlicePy(JNIEnv *env, jobject obj, jlong symPtr, jobjectArray keyStr, jbooleanArray status)
{
   u64_t rc_gmdFindLastRecordSlicePy;
   jfieldID fid;
   u64_t pgmd;
   jclass cls = (*env)->GetObjectClass(env, obj);
   u64_t local_symPtr;
   int i_keyStr, sidim_keyStr;
   stringUEL local_keyStr[GLOBAL_MAX_INDEX_DIM];
   char *ptr_keyStr[GLOBAL_MAX_INDEX_DIM];
   jboolean *local_status;
   int ib_status = 0;
   fid = (*env)->GetFieldID(env, cls, "gmdPtr", "J");
   if (fid == NULL) return (jlong) NULL;
   pgmd.i = (*env)->GetLongField(env, obj, fid);
   local_symPtr.i = symPtr;
   local_status = (*env)->GetBooleanArrayElements(env, status, NULL);
   if(local_status[0]) ib_status = 1;
   if(!gmdSymbolDim((gmdHandle_t)pgmd.p, local_symPtr.p, &sidim_keyStr)) return 0;
   for(i_keyStr=0;i_keyStr<sidim_keyStr;++i_keyStr) {
      jstring js_;
      char *str_;
      ptr_keyStr[i_keyStr] = local_keyStr[i_keyStr];
      js_ = (*env)->GetObjectArrayElement(env, keyStr, i_keyStr);
      if (js_==NULL)
          js_ = (*env)->NewStringUTF(env, "");
      str_ = (char*) (*env)->GetStringUTFChars(env, js_, NULL);
      strncpy(local_keyStr[i_keyStr], str_, GLOBAL_UEL_IDENT_SIZE-1);
      local_keyStr[i_keyStr][GLOBAL_UEL_IDENT_SIZE-1] = '\0';
      (*env)->ReleaseStringUTFChars(env, js_, str_);
   }
   rc_gmdFindLastRecordSlicePy.p = gmdFindLastRecordSlicePy((gmdHandle_t)pgmd.p, local_symPtr.p, ptr_keyStr, &ib_status);
   if(ib_status) local_status[0] = JNI_TRUE; else local_status[0] = JNI_FALSE;
   (*env)->ReleaseBooleanArrayElements(env, status, local_status, 0);
   return rc_gmdFindLastRecordSlicePy.i;
}

JNIEXPORT jboolean JNICALL Java_com_gams_api_gmd_RecordMoveNext(JNIEnv *env, jobject obj, jlong symIterPtr)
{
   int rc_gmdRecordMoveNext;
   jfieldID fid;
   u64_t pgmd;
   jclass cls = (*env)->GetObjectClass(env, obj);
   u64_t local_symIterPtr;
   fid = (*env)->GetFieldID(env, cls, "gmdPtr", "J");
   if (fid == NULL) return 0;
   pgmd.i = (*env)->GetLongField(env, obj, fid);
   local_symIterPtr.i = symIterPtr;
   rc_gmdRecordMoveNext = gmdRecordMoveNext((gmdHandle_t)pgmd.p, local_symIterPtr.p);
   return rc_gmdRecordMoveNext;
}

JNIEXPORT jboolean JNICALL Java_com_gams_api_gmd_RecordHasNext(JNIEnv *env, jobject obj, jlong symIterPtr)
{
   int rc_gmdRecordHasNext;
   jfieldID fid;
   u64_t pgmd;
   jclass cls = (*env)->GetObjectClass(env, obj);
   u64_t local_symIterPtr;
   fid = (*env)->GetFieldID(env, cls, "gmdPtr", "J");
   if (fid == NULL) return 0;
   pgmd.i = (*env)->GetLongField(env, obj, fid);
   local_symIterPtr.i = symIterPtr;
   rc_gmdRecordHasNext = gmdRecordHasNext((gmdHandle_t)pgmd.p, local_symIterPtr.p);
   return rc_gmdRecordHasNext;
}

JNIEXPORT jboolean JNICALL Java_com_gams_api_gmd_RecordMovePrev(JNIEnv *env, jobject obj, jlong symIterPtr)
{
   int rc_gmdRecordMovePrev;
   jfieldID fid;
   u64_t pgmd;
   jclass cls = (*env)->GetObjectClass(env, obj);
   u64_t local_symIterPtr;
   fid = (*env)->GetFieldID(env, cls, "gmdPtr", "J");
   if (fid == NULL) return 0;
   pgmd.i = (*env)->GetLongField(env, obj, fid);
   local_symIterPtr.i = symIterPtr;
   rc_gmdRecordMovePrev = gmdRecordMovePrev((gmdHandle_t)pgmd.p, local_symIterPtr.p);
   return rc_gmdRecordMovePrev;
}

JNIEXPORT jboolean JNICALL Java_com_gams_api_gmd_SameRecord(JNIEnv *env, jobject obj, jlong symIterPtrSrc, jlong symIterPtrtar)
{
   int rc_gmdSameRecord;
   jfieldID fid;
   u64_t pgmd;
   jclass cls = (*env)->GetObjectClass(env, obj);
   u64_t local_symIterPtrSrc;
   u64_t local_symIterPtrtar;
   fid = (*env)->GetFieldID(env, cls, "gmdPtr", "J");
   if (fid == NULL) return 0;
   pgmd.i = (*env)->GetLongField(env, obj, fid);
   local_symIterPtrSrc.i = symIterPtrSrc;
   local_symIterPtrtar.i = symIterPtrtar;
   rc_gmdSameRecord = gmdSameRecord((gmdHandle_t)pgmd.p, local_symIterPtrSrc.p, local_symIterPtrtar.p);
   return rc_gmdSameRecord;
}

JNIEXPORT jboolean JNICALL Java_com_gams_api_gmd_RecordHasPrev(JNIEnv *env, jobject obj, jlong symIterPtr)
{
   int rc_gmdRecordHasPrev;
   jfieldID fid;
   u64_t pgmd;
   jclass cls = (*env)->GetObjectClass(env, obj);
   u64_t local_symIterPtr;
   fid = (*env)->GetFieldID(env, cls, "gmdPtr", "J");
   if (fid == NULL) return 0;
   pgmd.i = (*env)->GetLongField(env, obj, fid);
   local_symIterPtr.i = symIterPtr;
   rc_gmdRecordHasPrev = gmdRecordHasPrev((gmdHandle_t)pgmd.p, local_symIterPtr.p);
   return rc_gmdRecordHasPrev;
}

JNIEXPORT jboolean JNICALL Java_com_gams_api_gmd_GetElemText(JNIEnv *env, jobject obj, jlong symIterPtr, jobjectArray txt)
{
   int rc_gmdGetElemText;
   jfieldID fid;
   u64_t pgmd;
   jclass cls = (*env)->GetObjectClass(env, obj);
   u64_t local_symIterPtr;
   jstring local_txt;
   char buffer_txt[256];
   fid = (*env)->GetFieldID(env, cls, "gmdPtr", "J");
   if (fid == NULL) return 0;
   pgmd.i = (*env)->GetLongField(env, obj, fid);
   local_symIterPtr.i = symIterPtr;
   buffer_txt[0] = '\0';
   rc_gmdGetElemText = gmdGetElemText((gmdHandle_t)pgmd.p, local_symIterPtr.p, buffer_txt);
   local_txt = (*env)->NewStringUTF(env, buffer_txt);
   (*env)->SetObjectArrayElement(env, txt, 0, local_txt);
   return rc_gmdGetElemText;
}

JNIEXPORT jboolean JNICALL Java_com_gams_api_gmd_GetLevel(JNIEnv *env, jobject obj, jlong symIterPtr, jdoubleArray value)
{
   int rc_gmdGetLevel;
   jfieldID fid;
   u64_t pgmd;
   jclass cls = (*env)->GetObjectClass(env, obj);
   u64_t local_symIterPtr;
   double local_value[1];
   fid = (*env)->GetFieldID(env, cls, "gmdPtr", "J");
   if (fid == NULL) return 0;
   pgmd.i = (*env)->GetLongField(env, obj, fid);
   local_symIterPtr.i = symIterPtr;
   rc_gmdGetLevel = gmdGetLevel((gmdHandle_t)pgmd.p, local_symIterPtr.p, local_value);
   (*env)->SetDoubleArrayRegion(env, value, 0, 1, local_value);
   return rc_gmdGetLevel;
}

JNIEXPORT jboolean JNICALL Java_com_gams_api_gmd_GetLower(JNIEnv *env, jobject obj, jlong symIterPtr, jdoubleArray value)
{
   int rc_gmdGetLower;
   jfieldID fid;
   u64_t pgmd;
   jclass cls = (*env)->GetObjectClass(env, obj);
   u64_t local_symIterPtr;
   double local_value[1];
   fid = (*env)->GetFieldID(env, cls, "gmdPtr", "J");
   if (fid == NULL) return 0;
   pgmd.i = (*env)->GetLongField(env, obj, fid);
   local_symIterPtr.i = symIterPtr;
   rc_gmdGetLower = gmdGetLower((gmdHandle_t)pgmd.p, local_symIterPtr.p, local_value);
   (*env)->SetDoubleArrayRegion(env, value, 0, 1, local_value);
   return rc_gmdGetLower;
}

JNIEXPORT jboolean JNICALL Java_com_gams_api_gmd_GetUpper(JNIEnv *env, jobject obj, jlong symIterPtr, jdoubleArray value)
{
   int rc_gmdGetUpper;
   jfieldID fid;
   u64_t pgmd;
   jclass cls = (*env)->GetObjectClass(env, obj);
   u64_t local_symIterPtr;
   double local_value[1];
   fid = (*env)->GetFieldID(env, cls, "gmdPtr", "J");
   if (fid == NULL) return 0;
   pgmd.i = (*env)->GetLongField(env, obj, fid);
   local_symIterPtr.i = symIterPtr;
   rc_gmdGetUpper = gmdGetUpper((gmdHandle_t)pgmd.p, local_symIterPtr.p, local_value);
   (*env)->SetDoubleArrayRegion(env, value, 0, 1, local_value);
   return rc_gmdGetUpper;
}

JNIEXPORT jboolean JNICALL Java_com_gams_api_gmd_GetMarginal(JNIEnv *env, jobject obj, jlong symIterPtr, jdoubleArray value)
{
   int rc_gmdGetMarginal;
   jfieldID fid;
   u64_t pgmd;
   jclass cls = (*env)->GetObjectClass(env, obj);
   u64_t local_symIterPtr;
   double local_value[1];
   fid = (*env)->GetFieldID(env, cls, "gmdPtr", "J");
   if (fid == NULL) return 0;
   pgmd.i = (*env)->GetLongField(env, obj, fid);
   local_symIterPtr.i = symIterPtr;
   rc_gmdGetMarginal = gmdGetMarginal((gmdHandle_t)pgmd.p, local_symIterPtr.p, local_value);
   (*env)->SetDoubleArrayRegion(env, value, 0, 1, local_value);
   return rc_gmdGetMarginal;
}

JNIEXPORT jboolean JNICALL Java_com_gams_api_gmd_GetScale(JNIEnv *env, jobject obj, jlong symIterPtr, jdoubleArray value)
{
   int rc_gmdGetScale;
   jfieldID fid;
   u64_t pgmd;
   jclass cls = (*env)->GetObjectClass(env, obj);
   u64_t local_symIterPtr;
   double local_value[1];
   fid = (*env)->GetFieldID(env, cls, "gmdPtr", "J");
   if (fid == NULL) return 0;
   pgmd.i = (*env)->GetLongField(env, obj, fid);
   local_symIterPtr.i = symIterPtr;
   rc_gmdGetScale = gmdGetScale((gmdHandle_t)pgmd.p, local_symIterPtr.p, local_value);
   (*env)->SetDoubleArrayRegion(env, value, 0, 1, local_value);
   return rc_gmdGetScale;
}

JNIEXPORT jboolean JNICALL Java_com_gams_api_gmd_SetElemText(JNIEnv *env, jobject obj, jlong symIterPtr, jstring txt)
{
   int rc_gmdSetElemText;
   jfieldID fid;
   u64_t pgmd;
   jclass cls = (*env)->GetObjectClass(env, obj);
   u64_t local_symIterPtr;
   char *local_txt;
   fid = (*env)->GetFieldID(env, cls, "gmdPtr", "J");
   if (fid == NULL) return 0;
   pgmd.i = (*env)->GetLongField(env, obj, fid);
   local_symIterPtr.i = symIterPtr;
   local_txt = (char *)(*env)->GetStringUTFChars(env, txt, NULL);
   rc_gmdSetElemText = gmdSetElemText((gmdHandle_t)pgmd.p, local_symIterPtr.p, local_txt);
   (*env)->ReleaseStringUTFChars(env, txt, local_txt);
   return rc_gmdSetElemText;
}

JNIEXPORT jboolean JNICALL Java_com_gams_api_gmd_SetLevel(JNIEnv *env, jobject obj, jlong symIterPtr, jdouble value)
{
   int rc_gmdSetLevel;
   jfieldID fid;
   u64_t pgmd;
   jclass cls = (*env)->GetObjectClass(env, obj);
   u64_t local_symIterPtr;
   fid = (*env)->GetFieldID(env, cls, "gmdPtr", "J");
   if (fid == NULL) return 0;
   pgmd.i = (*env)->GetLongField(env, obj, fid);
   local_symIterPtr.i = symIterPtr;
   rc_gmdSetLevel = gmdSetLevel((gmdHandle_t)pgmd.p, local_symIterPtr.p, value);
   return rc_gmdSetLevel;
}

JNIEXPORT jboolean JNICALL Java_com_gams_api_gmd_SetLower(JNIEnv *env, jobject obj, jlong symIterPtr, jdouble value)
{
   int rc_gmdSetLower;
   jfieldID fid;
   u64_t pgmd;
   jclass cls = (*env)->GetObjectClass(env, obj);
   u64_t local_symIterPtr;
   fid = (*env)->GetFieldID(env, cls, "gmdPtr", "J");
   if (fid == NULL) return 0;
   pgmd.i = (*env)->GetLongField(env, obj, fid);
   local_symIterPtr.i = symIterPtr;
   rc_gmdSetLower = gmdSetLower((gmdHandle_t)pgmd.p, local_symIterPtr.p, value);
   return rc_gmdSetLower;
}

JNIEXPORT jboolean JNICALL Java_com_gams_api_gmd_SetUpper(JNIEnv *env, jobject obj, jlong symIterPtr, jdouble value)
{
   int rc_gmdSetUpper;
   jfieldID fid;
   u64_t pgmd;
   jclass cls = (*env)->GetObjectClass(env, obj);
   u64_t local_symIterPtr;
   fid = (*env)->GetFieldID(env, cls, "gmdPtr", "J");
   if (fid == NULL) return 0;
   pgmd.i = (*env)->GetLongField(env, obj, fid);
   local_symIterPtr.i = symIterPtr;
   rc_gmdSetUpper = gmdSetUpper((gmdHandle_t)pgmd.p, local_symIterPtr.p, value);
   return rc_gmdSetUpper;
}

JNIEXPORT jboolean JNICALL Java_com_gams_api_gmd_SetMarginal(JNIEnv *env, jobject obj, jlong symIterPtr, jdouble value)
{
   int rc_gmdSetMarginal;
   jfieldID fid;
   u64_t pgmd;
   jclass cls = (*env)->GetObjectClass(env, obj);
   u64_t local_symIterPtr;
   fid = (*env)->GetFieldID(env, cls, "gmdPtr", "J");
   if (fid == NULL) return 0;
   pgmd.i = (*env)->GetLongField(env, obj, fid);
   local_symIterPtr.i = symIterPtr;
   rc_gmdSetMarginal = gmdSetMarginal((gmdHandle_t)pgmd.p, local_symIterPtr.p, value);
   return rc_gmdSetMarginal;
}

JNIEXPORT jboolean JNICALL Java_com_gams_api_gmd_SetScale(JNIEnv *env, jobject obj, jlong symIterPtr, jdouble value)
{
   int rc_gmdSetScale;
   jfieldID fid;
   u64_t pgmd;
   jclass cls = (*env)->GetObjectClass(env, obj);
   u64_t local_symIterPtr;
   fid = (*env)->GetFieldID(env, cls, "gmdPtr", "J");
   if (fid == NULL) return 0;
   pgmd.i = (*env)->GetLongField(env, obj, fid);
   local_symIterPtr.i = symIterPtr;
   rc_gmdSetScale = gmdSetScale((gmdHandle_t)pgmd.p, local_symIterPtr.p, value);
   return rc_gmdSetScale;
}

JNIEXPORT jboolean JNICALL Java_com_gams_api_gmd_SetUserInfo(JNIEnv *env, jobject obj, jlong symPtr, jint value)
{
   int rc_gmdSetUserInfo;
   jfieldID fid;
   u64_t pgmd;
   jclass cls = (*env)->GetObjectClass(env, obj);
   u64_t local_symPtr;
   fid = (*env)->GetFieldID(env, cls, "gmdPtr", "J");
   if (fid == NULL) return 0;
   pgmd.i = (*env)->GetLongField(env, obj, fid);
   local_symPtr.i = symPtr;
   rc_gmdSetUserInfo = gmdSetUserInfo((gmdHandle_t)pgmd.p, local_symPtr.p, value);
   return rc_gmdSetUserInfo;
}

JNIEXPORT jboolean JNICALL Java_com_gams_api_gmd_AddRecord(JNIEnv *env, jobject obj, jlong symPtr, jobjectArray keyStr, jlongArray symIterPtr)
{
   int rc_gmdAddRecord;
   jfieldID fid;
   u64_t pgmd;
   jclass cls = (*env)->GetObjectClass(env, obj);
   u64_t local_symPtr;
   int i_keyStr, sidim_keyStr;
   stringUEL local_keyStr[GLOBAL_MAX_INDEX_DIM];
   char *ptr_keyStr[GLOBAL_MAX_INDEX_DIM];
   jlong* local_symIterPtr;
   void** localCopy_symIterPtr;
   fid = (*env)->GetFieldID(env, cls, "gmdPtr", "J");
   if (fid == NULL) return 0;
   pgmd.i = (*env)->GetLongField(env, obj, fid);
   local_symPtr.i = symPtr;
   local_symIterPtr = (*env)->GetLongArrayElements(env, symIterPtr, NULL);
   if( sizeof(jlong) != sizeof(void*) ) {
     jsize localCount;
     u64_t blab;
     localCopy_symIterPtr = (void**)malloc(sizeof(void*) * (*env)->GetArrayLength(env, symIterPtr));
     for( localCount = 0; localCount < (*env)->GetArrayLength(env, symIterPtr); ++localCount ) {
       blab.i = local_symIterPtr[localCount];
       localCopy_symIterPtr[localCount] = blab.p;
       }
   } else
     localCopy_symIterPtr = (void**)local_symIterPtr;
   if(!gmdSymbolDim((gmdHandle_t)pgmd.p, local_symPtr.p, &sidim_keyStr)) return 0;
   for(i_keyStr=0;i_keyStr<sidim_keyStr;++i_keyStr) {
      jstring js_;
      char *str_;
      ptr_keyStr[i_keyStr] = local_keyStr[i_keyStr];
      js_ = (*env)->GetObjectArrayElement(env, keyStr, i_keyStr);
      if (js_==NULL)
          js_ = (*env)->NewStringUTF(env, "");
      str_ = (char*) (*env)->GetStringUTFChars(env, js_, NULL);
      strncpy(local_keyStr[i_keyStr], str_, GLOBAL_UEL_IDENT_SIZE-1);
      local_keyStr[i_keyStr][GLOBAL_UEL_IDENT_SIZE-1] = '\0';
      (*env)->ReleaseStringUTFChars(env, js_, str_);
   }
   rc_gmdAddRecord = gmdAddRecord((gmdHandle_t)pgmd.p, local_symPtr.p, ptr_keyStr, localCopy_symIterPtr);
   (*env)->ReleaseLongArrayElements(env, symIterPtr, local_symIterPtr, 0);
   if( sizeof(jlong) != sizeof(void*) ) {
     jsize localCount;
     u64_t blub;
     for( localCount = 0; localCount < (*env)->GetArrayLength(env, symIterPtr); ++localCount ) {
       blub.i = 0; blub.p = localCopy_symIterPtr[localCount];
       (*env)->SetLongArrayRegion(env, symIterPtr, localCount, 1, &blub.i);
     }
     free(localCopy_symIterPtr);
   }
   return rc_gmdAddRecord;
}

JNIEXPORT jlong JNICALL Java_com_gams_api_gmd_AddRecordPy(JNIEnv *env, jobject obj, jlong symPtr, jobjectArray keyStr, jbooleanArray status)
{
   u64_t rc_gmdAddRecordPy;
   jfieldID fid;
   u64_t pgmd;
   jclass cls = (*env)->GetObjectClass(env, obj);
   u64_t local_symPtr;
   int i_keyStr, sidim_keyStr;
   stringUEL local_keyStr[GLOBAL_MAX_INDEX_DIM];
   char *ptr_keyStr[GLOBAL_MAX_INDEX_DIM];
   jboolean *local_status;
   int ib_status = 0;
   fid = (*env)->GetFieldID(env, cls, "gmdPtr", "J");
   if (fid == NULL) return (jlong) NULL;
   pgmd.i = (*env)->GetLongField(env, obj, fid);
   local_symPtr.i = symPtr;
   local_status = (*env)->GetBooleanArrayElements(env, status, NULL);
   if(local_status[0]) ib_status = 1;
   if(!gmdSymbolDim((gmdHandle_t)pgmd.p, local_symPtr.p, &sidim_keyStr)) return 0;
   for(i_keyStr=0;i_keyStr<sidim_keyStr;++i_keyStr) {
      jstring js_;
      char *str_;
      ptr_keyStr[i_keyStr] = local_keyStr[i_keyStr];
      js_ = (*env)->GetObjectArrayElement(env, keyStr, i_keyStr);
      if (js_==NULL)
          js_ = (*env)->NewStringUTF(env, "");
      str_ = (char*) (*env)->GetStringUTFChars(env, js_, NULL);
      strncpy(local_keyStr[i_keyStr], str_, GLOBAL_UEL_IDENT_SIZE-1);
      local_keyStr[i_keyStr][GLOBAL_UEL_IDENT_SIZE-1] = '\0';
      (*env)->ReleaseStringUTFChars(env, js_, str_);
   }
   rc_gmdAddRecordPy.p = gmdAddRecordPy((gmdHandle_t)pgmd.p, local_symPtr.p, ptr_keyStr, &ib_status);
   if(ib_status) local_status[0] = JNI_TRUE; else local_status[0] = JNI_FALSE;
   (*env)->ReleaseBooleanArrayElements(env, status, local_status, 0);
   return rc_gmdAddRecordPy.i;
}

JNIEXPORT jboolean JNICALL Java_com_gams_api_gmd_DeleteRecord(JNIEnv *env, jobject obj, jlong symIterPtr)
{
   int rc_gmdDeleteRecord;
   jfieldID fid;
   u64_t pgmd;
   jclass cls = (*env)->GetObjectClass(env, obj);
   u64_t local_symIterPtr;
   fid = (*env)->GetFieldID(env, cls, "gmdPtr", "J");
   if (fid == NULL) return 0;
   pgmd.i = (*env)->GetLongField(env, obj, fid);
   local_symIterPtr.i = symIterPtr;
   rc_gmdDeleteRecord = gmdDeleteRecord((gmdHandle_t)pgmd.p, local_symIterPtr.p);
   return rc_gmdDeleteRecord;
}

JNIEXPORT jboolean JNICALL Java_com_gams_api_gmd_GetKeys(JNIEnv *env, jobject obj, jlong symIterPtr, jint aDim, jobjectArray keyStr)
{
   int rc_gmdGetKeys;
   jfieldID fid;
   u64_t pgmd;
   jclass cls = (*env)->GetObjectClass(env, obj);
   u64_t local_symIterPtr;
   int i_keyStr, sidim_keyStr;
   stringUEL local_keyStr[GLOBAL_MAX_INDEX_DIM];
   char *ptr_keyStr[GLOBAL_MAX_INDEX_DIM];
   fid = (*env)->GetFieldID(env, cls, "gmdPtr", "J");
   if (fid == NULL) return 0;
   pgmd.i = (*env)->GetLongField(env, obj, fid);
   local_symIterPtr.i = symIterPtr;
   sidim_keyStr = aDim;
   for(i_keyStr=0;i_keyStr<sidim_keyStr;++i_keyStr) {
      jstring js_;
      char *str_;
      ptr_keyStr[i_keyStr] = local_keyStr[i_keyStr];
   }
   rc_gmdGetKeys = gmdGetKeys((gmdHandle_t)pgmd.p, local_symIterPtr.p, aDim, ptr_keyStr);
   sidim_keyStr = aDim;
   for(i_keyStr=0;i_keyStr<sidim_keyStr;++i_keyStr) {
      jstring js_;
      js_ = (*env)->NewStringUTF(env, local_keyStr[i_keyStr]);
      (*env)->SetObjectArrayElement(env, keyStr, i_keyStr, js_);
   }
   return rc_gmdGetKeys;
}

JNIEXPORT jboolean JNICALL Java_com_gams_api_gmd_GetKey(JNIEnv *env, jobject obj, jlong symIterPtr, jint idx, jobjectArray keyStr)
{
   int rc_gmdGetKey;
   jfieldID fid;
   u64_t pgmd;
   jclass cls = (*env)->GetObjectClass(env, obj);
   u64_t local_symIterPtr;
   jstring local_keyStr;
   char buffer_keyStr[256];
   fid = (*env)->GetFieldID(env, cls, "gmdPtr", "J");
   if (fid == NULL) return 0;
   pgmd.i = (*env)->GetLongField(env, obj, fid);
   local_symIterPtr.i = symIterPtr;
   buffer_keyStr[0] = '\0';
   rc_gmdGetKey = gmdGetKey((gmdHandle_t)pgmd.p, local_symIterPtr.p, idx, buffer_keyStr);
   local_keyStr = (*env)->NewStringUTF(env, buffer_keyStr);
   (*env)->SetObjectArrayElement(env, keyStr, 0, local_keyStr);
   return rc_gmdGetKey;
}

JNIEXPORT jboolean JNICALL Java_com_gams_api_gmd_GetDomain(JNIEnv *env, jobject obj, jlong symPtr, jint aDim, jlongArray vDomPtrOut, jobjectArray keyStr)
{
   int rc_gmdGetDomain;
   jfieldID fid;
   u64_t pgmd;
   jclass cls = (*env)->GetObjectClass(env, obj);
   u64_t local_symPtr;
   jlong* local_vDomPtrOut;
   void** localCopy_vDomPtrOut;
   int i_keyStr, sidim_keyStr;
   stringUEL local_keyStr[GLOBAL_MAX_INDEX_DIM];
   char *ptr_keyStr[GLOBAL_MAX_INDEX_DIM];
   fid = (*env)->GetFieldID(env, cls, "gmdPtr", "J");
   if (fid == NULL) return 0;
   pgmd.i = (*env)->GetLongField(env, obj, fid);
   local_symPtr.i = symPtr;
   local_vDomPtrOut = (*env)->GetLongArrayElements(env, vDomPtrOut, NULL);
   if( sizeof(jlong) != sizeof(void*) ) {
     jsize localCount;
     u64_t blab;
     localCopy_vDomPtrOut = (void**)malloc(sizeof(void*) * (*env)->GetArrayLength(env, vDomPtrOut));
     for( localCount = 0; localCount < (*env)->GetArrayLength(env, vDomPtrOut); ++localCount ) {
       blab.i = local_vDomPtrOut[localCount];
       localCopy_vDomPtrOut[localCount] = blab.p;
       }
   } else
     localCopy_vDomPtrOut = (void**)local_vDomPtrOut;
   sidim_keyStr = aDim;
   for(i_keyStr=0;i_keyStr<sidim_keyStr;++i_keyStr) {
      jstring js_;
      char *str_;
      ptr_keyStr[i_keyStr] = local_keyStr[i_keyStr];
   }
   rc_gmdGetDomain = gmdGetDomain((gmdHandle_t)pgmd.p, local_symPtr.p, aDim, localCopy_vDomPtrOut, ptr_keyStr);
   (*env)->ReleaseLongArrayElements(env, vDomPtrOut, local_vDomPtrOut, 0);
   if( sizeof(jlong) != sizeof(void*) ) {
     jsize localCount;
     u64_t blub;
     for( localCount = 0; localCount < (*env)->GetArrayLength(env, vDomPtrOut); ++localCount ) {
       blub.i = 0; blub.p = localCopy_vDomPtrOut[localCount];
       (*env)->SetLongArrayRegion(env, vDomPtrOut, localCount, 1, &blub.i);
     }
     free(localCopy_vDomPtrOut);
   }
   sidim_keyStr = aDim;
   for(i_keyStr=0;i_keyStr<sidim_keyStr;++i_keyStr) {
      jstring js_;
      js_ = (*env)->NewStringUTF(env, local_keyStr[i_keyStr]);
      (*env)->SetObjectArrayElement(env, keyStr, i_keyStr, js_);
   }
   return rc_gmdGetDomain;
}

JNIEXPORT jboolean JNICALL Java_com_gams_api_gmd_CopySymbolIterator(JNIEnv *env, jobject obj, jlong symIterPtrSrc, jlongArray symIterPtrtar)
{
   int rc_gmdCopySymbolIterator;
   jfieldID fid;
   u64_t pgmd;
   jclass cls = (*env)->GetObjectClass(env, obj);
   u64_t local_symIterPtrSrc;
   jlong* local_symIterPtrtar;
   void** localCopy_symIterPtrtar;
   fid = (*env)->GetFieldID(env, cls, "gmdPtr", "J");
   if (fid == NULL) return 0;
   pgmd.i = (*env)->GetLongField(env, obj, fid);
   local_symIterPtrSrc.i = symIterPtrSrc;
   local_symIterPtrtar = (*env)->GetLongArrayElements(env, symIterPtrtar, NULL);
   if( sizeof(jlong) != sizeof(void*) ) {
     jsize localCount;
     u64_t blab;
     localCopy_symIterPtrtar = (void**)malloc(sizeof(void*) * (*env)->GetArrayLength(env, symIterPtrtar));
     for( localCount = 0; localCount < (*env)->GetArrayLength(env, symIterPtrtar); ++localCount ) {
       blab.i = local_symIterPtrtar[localCount];
       localCopy_symIterPtrtar[localCount] = blab.p;
       }
   } else
     localCopy_symIterPtrtar = (void**)local_symIterPtrtar;
   rc_gmdCopySymbolIterator = gmdCopySymbolIterator((gmdHandle_t)pgmd.p, local_symIterPtrSrc.p, localCopy_symIterPtrtar);
   (*env)->ReleaseLongArrayElements(env, symIterPtrtar, local_symIterPtrtar, 0);
   if( sizeof(jlong) != sizeof(void*) ) {
     jsize localCount;
     u64_t blub;
     for( localCount = 0; localCount < (*env)->GetArrayLength(env, symIterPtrtar); ++localCount ) {
       blub.i = 0; blub.p = localCopy_symIterPtrtar[localCount];
       (*env)->SetLongArrayRegion(env, symIterPtrtar, localCount, 1, &blub.i);
     }
     free(localCopy_symIterPtrtar);
   }
   return rc_gmdCopySymbolIterator;
}

JNIEXPORT jlong JNICALL Java_com_gams_api_gmd_CopySymbolIteratorPy(JNIEnv *env, jobject obj, jlong symIterPtrSrc, jbooleanArray status)
{
   u64_t rc_gmdCopySymbolIteratorPy;
   jfieldID fid;
   u64_t pgmd;
   jclass cls = (*env)->GetObjectClass(env, obj);
   u64_t local_symIterPtrSrc;
   jboolean *local_status;
   int ib_status = 0;
   fid = (*env)->GetFieldID(env, cls, "gmdPtr", "J");
   if (fid == NULL) return (jlong) NULL;
   pgmd.i = (*env)->GetLongField(env, obj, fid);
   local_symIterPtrSrc.i = symIterPtrSrc;
   local_status = (*env)->GetBooleanArrayElements(env, status, NULL);
   if(local_status[0]) ib_status = 1;
   rc_gmdCopySymbolIteratorPy.p = gmdCopySymbolIteratorPy((gmdHandle_t)pgmd.p, local_symIterPtrSrc.p, &ib_status);
   if(ib_status) local_status[0] = JNI_TRUE; else local_status[0] = JNI_FALSE;
   (*env)->ReleaseBooleanArrayElements(env, status, local_status, 0);
   return rc_gmdCopySymbolIteratorPy.i;
}

JNIEXPORT jboolean JNICALL Java_com_gams_api_gmd_FreeSymbolIterator(JNIEnv *env, jclass cls, jlong symIterPtr)
{
   int rc_gmdFreeSymbolIterator;
   u64_t local_symIterPtr;
   local_symIterPtr.i = symIterPtr;
   rc_gmdFreeSymbolIterator = gmdFreeSymbolIterator(NULL, local_symIterPtr.p);
   return rc_gmdFreeSymbolIterator;
}

JNIEXPORT jboolean JNICALL Java_com_gams_api_gmd_MergeUel(JNIEnv *env, jobject obj, jstring uel, jintArray uelNr)
{
   int rc_gmdMergeUel;
   jfieldID fid;
   u64_t pgmd;
   jclass cls = (*env)->GetObjectClass(env, obj);
   char *local_uel;
   int local_uelNr[1];
   fid = (*env)->GetFieldID(env, cls, "gmdPtr", "J");
   if (fid == NULL) return 0;
   pgmd.i = (*env)->GetLongField(env, obj, fid);
   local_uel = (char *)(*env)->GetStringUTFChars(env, uel, NULL);
   rc_gmdMergeUel = gmdMergeUel((gmdHandle_t)pgmd.p, local_uel, local_uelNr);
   (*env)->ReleaseStringUTFChars(env, uel, local_uel);
   (*env)->SetIntArrayRegion(env, uelNr, 0, 1, local_uelNr);
   return rc_gmdMergeUel;
}

JNIEXPORT jboolean JNICALL Java_com_gams_api_gmd_Info(JNIEnv *env, jobject obj, jint infoKey, jintArray ival, jdoubleArray dval, jobjectArray sval)
{
   int rc_gmdInfo;
   jfieldID fid;
   u64_t pgmd;
   jclass cls = (*env)->GetObjectClass(env, obj);
   int local_ival[1];
   double local_dval[1];
   jstring local_sval;
   char buffer_sval[256];
   fid = (*env)->GetFieldID(env, cls, "gmdPtr", "J");
   if (fid == NULL) return 0;
   pgmd.i = (*env)->GetLongField(env, obj, fid);
   buffer_sval[0] = '\0';
   rc_gmdInfo = gmdInfo((gmdHandle_t)pgmd.p, infoKey, local_ival, local_dval, buffer_sval);
   (*env)->SetIntArrayRegion(env, ival, 0, 1, local_ival);
   (*env)->SetDoubleArrayRegion(env, dval, 0, 1, local_dval);
   local_sval = (*env)->NewStringUTF(env, buffer_sval);
   (*env)->SetObjectArrayElement(env, sval, 0, local_sval);
   return rc_gmdInfo;
}

JNIEXPORT jboolean JNICALL Java_com_gams_api_gmd_SymbolInfo(JNIEnv *env, jobject obj, jlong symPtr, jint infoKey, jintArray ival, jdoubleArray dval, jobjectArray sval)
{
   int rc_gmdSymbolInfo;
   jfieldID fid;
   u64_t pgmd;
   jclass cls = (*env)->GetObjectClass(env, obj);
   u64_t local_symPtr;
   int local_ival[1];
   double local_dval[1];
   jstring local_sval;
   char buffer_sval[256];
   fid = (*env)->GetFieldID(env, cls, "gmdPtr", "J");
   if (fid == NULL) return 0;
   pgmd.i = (*env)->GetLongField(env, obj, fid);
   local_symPtr.i = symPtr;
   buffer_sval[0] = '\0';
   rc_gmdSymbolInfo = gmdSymbolInfo((gmdHandle_t)pgmd.p, local_symPtr.p, infoKey, local_ival, local_dval, buffer_sval);
   (*env)->SetIntArrayRegion(env, ival, 0, 1, local_ival);
   (*env)->SetDoubleArrayRegion(env, dval, 0, 1, local_dval);
   local_sval = (*env)->NewStringUTF(env, buffer_sval);
   (*env)->SetObjectArrayElement(env, sval, 0, local_sval);
   return rc_gmdSymbolInfo;
}

JNIEXPORT jboolean JNICALL Java_com_gams_api_gmd_SymbolDim(JNIEnv *env, jobject obj, jlong symPtr, jintArray aDim)
{
   int rc_gmdSymbolDim;
   jfieldID fid;
   u64_t pgmd;
   jclass cls = (*env)->GetObjectClass(env, obj);
   u64_t local_symPtr;
   int local_aDim[1];
   fid = (*env)->GetFieldID(env, cls, "gmdPtr", "J");
   if (fid == NULL) return 0;
   pgmd.i = (*env)->GetLongField(env, obj, fid);
   local_symPtr.i = symPtr;
   rc_gmdSymbolDim = gmdSymbolDim((gmdHandle_t)pgmd.p, local_symPtr.p, local_aDim);
   (*env)->SetIntArrayRegion(env, aDim, 0, 1, local_aDim);
   return rc_gmdSymbolDim;
}

JNIEXPORT jboolean JNICALL Java_com_gams_api_gmd_SymbolType(JNIEnv *env, jobject obj, jlong symPtr, jintArray stype)
{
   int rc_gmdSymbolType;
   jfieldID fid;
   u64_t pgmd;
   jclass cls = (*env)->GetObjectClass(env, obj);
   u64_t local_symPtr;
   int local_stype[1];
   fid = (*env)->GetFieldID(env, cls, "gmdPtr", "J");
   if (fid == NULL) return 0;
   pgmd.i = (*env)->GetLongField(env, obj, fid);
   local_symPtr.i = symPtr;
   rc_gmdSymbolType = gmdSymbolType((gmdHandle_t)pgmd.p, local_symPtr.p, local_stype);
   (*env)->SetIntArrayRegion(env, stype, 0, 1, local_stype);
   return rc_gmdSymbolType;
}

JNIEXPORT jboolean JNICALL Java_com_gams_api_gmd_WriteGDX(JNIEnv *env, jobject obj, jstring fileName, jboolean noDomChk)
{
   int rc_gmdWriteGDX;
   jfieldID fid;
   u64_t pgmd;
   jclass cls = (*env)->GetObjectClass(env, obj);
   char *local_fileName;
   fid = (*env)->GetFieldID(env, cls, "gmdPtr", "J");
   if (fid == NULL) return 0;
   pgmd.i = (*env)->GetLongField(env, obj, fid);
   local_fileName = (char *)(*env)->GetStringUTFChars(env, fileName, NULL);
   rc_gmdWriteGDX = gmdWriteGDX((gmdHandle_t)pgmd.p, local_fileName, noDomChk);
   (*env)->ReleaseStringUTFChars(env, fileName, local_fileName);
   return rc_gmdWriteGDX;
}

JNIEXPORT jboolean JNICALL Java_com_gams_api_gmd_SetSpecialValues(JNIEnv *env, jobject obj, jdoubleArray specVal)
{
   int rc_gmdSetSpecialValues;
   jfieldID fid;
   u64_t pgmd;
   jclass cls = (*env)->GetObjectClass(env, obj);
   double *local_specVal;
   fid = (*env)->GetFieldID(env, cls, "gmdPtr", "J");
   if (fid == NULL) return 0;
   pgmd.i = (*env)->GetLongField(env, obj, fid);
   local_specVal = (*env)->GetDoubleArrayElements(env, specVal, NULL);
   rc_gmdSetSpecialValues = gmdSetSpecialValues((gmdHandle_t)pgmd.p, local_specVal);
   (*env)->ReleaseDoubleArrayElements(env, specVal, local_specVal, 0);
   return rc_gmdSetSpecialValues;
}

JNIEXPORT jboolean JNICALL Java_com_gams_api_gmd_SetDebug(JNIEnv *env, jobject obj, jint debugLevel)
{
   int rc_gmdSetDebug;
   jfieldID fid;
   u64_t pgmd;
   jclass cls = (*env)->GetObjectClass(env, obj);
   fid = (*env)->GetFieldID(env, cls, "gmdPtr", "J");
   if (fid == NULL) return 0;
   pgmd.i = (*env)->GetLongField(env, obj, fid);
   rc_gmdSetDebug = gmdSetDebug((gmdHandle_t)pgmd.p, debugLevel);
   return rc_gmdSetDebug;
}

JNIEXPORT jboolean JNICALL Java_com_gams_api_gmd_GetLastError(JNIEnv *env, jobject obj, jobjectArray msg)
{
   int rc_gmdGetLastError;
   jfieldID fid;
   u64_t pgmd;
   jclass cls = (*env)->GetObjectClass(env, obj);
   jstring local_msg;
   char buffer_msg[256];
   fid = (*env)->GetFieldID(env, cls, "gmdPtr", "J");
   if (fid == NULL) return 0;
   pgmd.i = (*env)->GetLongField(env, obj, fid);
   buffer_msg[0] = '\0';
   rc_gmdGetLastError = gmdGetLastError((gmdHandle_t)pgmd.p, buffer_msg);
   local_msg = (*env)->NewStringUTF(env, buffer_msg);
   (*env)->SetObjectArrayElement(env, msg, 0, local_msg);
   return rc_gmdGetLastError;
}

JNIEXPORT jboolean JNICALL Java_com_gams_api_gmd_CheckDBDV(JNIEnv *env, jobject obj, jbooleanArray dv)
{
   int rc_gmdCheckDBDV;
   jfieldID fid;
   u64_t pgmd;
   jclass cls = (*env)->GetObjectClass(env, obj);
   jboolean *local_dv;
   int ib_dv = 0;
   fid = (*env)->GetFieldID(env, cls, "gmdPtr", "J");
   if (fid == NULL) return 0;
   pgmd.i = (*env)->GetLongField(env, obj, fid);
   local_dv = (*env)->GetBooleanArrayElements(env, dv, NULL);
   if(local_dv[0]) ib_dv = 1;
   rc_gmdCheckDBDV = gmdCheckDBDV((gmdHandle_t)pgmd.p, &ib_dv);
   if(ib_dv) local_dv[0] = JNI_TRUE; else local_dv[0] = JNI_FALSE;
   (*env)->ReleaseBooleanArrayElements(env, dv, local_dv, 0);
   return rc_gmdCheckDBDV;
}

JNIEXPORT jboolean JNICALL Java_com_gams_api_gmd_CheckSymbolDV(JNIEnv *env, jobject obj, jlong symPtr, jbooleanArray dv)
{
   int rc_gmdCheckSymbolDV;
   jfieldID fid;
   u64_t pgmd;
   jclass cls = (*env)->GetObjectClass(env, obj);
   u64_t local_symPtr;
   jboolean *local_dv;
   int ib_dv = 0;
   fid = (*env)->GetFieldID(env, cls, "gmdPtr", "J");
   if (fid == NULL) return 0;
   pgmd.i = (*env)->GetLongField(env, obj, fid);
   local_symPtr.i = symPtr;
   local_dv = (*env)->GetBooleanArrayElements(env, dv, NULL);
   if(local_dv[0]) ib_dv = 1;
   rc_gmdCheckSymbolDV = gmdCheckSymbolDV((gmdHandle_t)pgmd.p, local_symPtr.p, &ib_dv);
   if(ib_dv) local_dv[0] = JNI_TRUE; else local_dv[0] = JNI_FALSE;
   (*env)->ReleaseBooleanArrayElements(env, dv, local_dv, 0);
   return rc_gmdCheckSymbolDV;
}

JNIEXPORT jboolean JNICALL Java_com_gams_api_gmd_GetFirstDBDV(JNIEnv *env, jobject obj, jlongArray dvHandle)
{
   int rc_gmdGetFirstDBDV;
   jfieldID fid;
   u64_t pgmd;
   jclass cls = (*env)->GetObjectClass(env, obj);
   jlong* local_dvHandle;
   void** localCopy_dvHandle;
   fid = (*env)->GetFieldID(env, cls, "gmdPtr", "J");
   if (fid == NULL) return 0;
   pgmd.i = (*env)->GetLongField(env, obj, fid);
   local_dvHandle = (*env)->GetLongArrayElements(env, dvHandle, NULL);
   if( sizeof(jlong) != sizeof(void*) ) {
     jsize localCount;
     u64_t blab;
     localCopy_dvHandle = (void**)malloc(sizeof(void*) * (*env)->GetArrayLength(env, dvHandle));
     for( localCount = 0; localCount < (*env)->GetArrayLength(env, dvHandle); ++localCount ) {
       blab.i = local_dvHandle[localCount];
       localCopy_dvHandle[localCount] = blab.p;
       }
   } else
     localCopy_dvHandle = (void**)local_dvHandle;
   rc_gmdGetFirstDBDV = gmdGetFirstDBDV((gmdHandle_t)pgmd.p, localCopy_dvHandle);
   (*env)->ReleaseLongArrayElements(env, dvHandle, local_dvHandle, 0);
   if( sizeof(jlong) != sizeof(void*) ) {
     jsize localCount;
     u64_t blub;
     for( localCount = 0; localCount < (*env)->GetArrayLength(env, dvHandle); ++localCount ) {
       blub.i = 0; blub.p = localCopy_dvHandle[localCount];
       (*env)->SetLongArrayRegion(env, dvHandle, localCount, 1, &blub.i);
     }
     free(localCopy_dvHandle);
   }
   return rc_gmdGetFirstDBDV;
}

JNIEXPORT jlong JNICALL Java_com_gams_api_gmd_GetFirstDBDVPy(JNIEnv *env, jobject obj, jbooleanArray status)
{
   u64_t rc_gmdGetFirstDBDVPy;
   jfieldID fid;
   u64_t pgmd;
   jclass cls = (*env)->GetObjectClass(env, obj);
   jboolean *local_status;
   int ib_status = 0;
   fid = (*env)->GetFieldID(env, cls, "gmdPtr", "J");
   if (fid == NULL) return (jlong) NULL;
   pgmd.i = (*env)->GetLongField(env, obj, fid);
   local_status = (*env)->GetBooleanArrayElements(env, status, NULL);
   if(local_status[0]) ib_status = 1;
   rc_gmdGetFirstDBDVPy.p = gmdGetFirstDBDVPy((gmdHandle_t)pgmd.p, &ib_status);
   if(ib_status) local_status[0] = JNI_TRUE; else local_status[0] = JNI_FALSE;
   (*env)->ReleaseBooleanArrayElements(env, status, local_status, 0);
   return rc_gmdGetFirstDBDVPy.i;
}

JNIEXPORT jboolean JNICALL Java_com_gams_api_gmd_GetFirstDVInSymbol(JNIEnv *env, jobject obj, jlong symPtr, jlongArray dvHandle)
{
   int rc_gmdGetFirstDVInSymbol;
   jfieldID fid;
   u64_t pgmd;
   jclass cls = (*env)->GetObjectClass(env, obj);
   u64_t local_symPtr;
   jlong* local_dvHandle;
   void** localCopy_dvHandle;
   fid = (*env)->GetFieldID(env, cls, "gmdPtr", "J");
   if (fid == NULL) return 0;
   pgmd.i = (*env)->GetLongField(env, obj, fid);
   local_symPtr.i = symPtr;
   local_dvHandle = (*env)->GetLongArrayElements(env, dvHandle, NULL);
   if( sizeof(jlong) != sizeof(void*) ) {
     jsize localCount;
     u64_t blab;
     localCopy_dvHandle = (void**)malloc(sizeof(void*) * (*env)->GetArrayLength(env, dvHandle));
     for( localCount = 0; localCount < (*env)->GetArrayLength(env, dvHandle); ++localCount ) {
       blab.i = local_dvHandle[localCount];
       localCopy_dvHandle[localCount] = blab.p;
       }
   } else
     localCopy_dvHandle = (void**)local_dvHandle;
   rc_gmdGetFirstDVInSymbol = gmdGetFirstDVInSymbol((gmdHandle_t)pgmd.p, local_symPtr.p, localCopy_dvHandle);
   (*env)->ReleaseLongArrayElements(env, dvHandle, local_dvHandle, 0);
   if( sizeof(jlong) != sizeof(void*) ) {
     jsize localCount;
     u64_t blub;
     for( localCount = 0; localCount < (*env)->GetArrayLength(env, dvHandle); ++localCount ) {
       blub.i = 0; blub.p = localCopy_dvHandle[localCount];
       (*env)->SetLongArrayRegion(env, dvHandle, localCount, 1, &blub.i);
     }
     free(localCopy_dvHandle);
   }
   return rc_gmdGetFirstDVInSymbol;
}

JNIEXPORT jlong JNICALL Java_com_gams_api_gmd_GetFirstDVInSymbolPy(JNIEnv *env, jobject obj, jlong symPtr, jbooleanArray status)
{
   u64_t rc_gmdGetFirstDVInSymbolPy;
   jfieldID fid;
   u64_t pgmd;
   jclass cls = (*env)->GetObjectClass(env, obj);
   u64_t local_symPtr;
   jboolean *local_status;
   int ib_status = 0;
   fid = (*env)->GetFieldID(env, cls, "gmdPtr", "J");
   if (fid == NULL) return (jlong) NULL;
   pgmd.i = (*env)->GetLongField(env, obj, fid);
   local_symPtr.i = symPtr;
   local_status = (*env)->GetBooleanArrayElements(env, status, NULL);
   if(local_status[0]) ib_status = 1;
   rc_gmdGetFirstDVInSymbolPy.p = gmdGetFirstDVInSymbolPy((gmdHandle_t)pgmd.p, local_symPtr.p, &ib_status);
   if(ib_status) local_status[0] = JNI_TRUE; else local_status[0] = JNI_FALSE;
   (*env)->ReleaseBooleanArrayElements(env, status, local_status, 0);
   return rc_gmdGetFirstDVInSymbolPy.i;
}

JNIEXPORT jboolean JNICALL Java_com_gams_api_gmd_DomainCheckDone(JNIEnv *env, jobject obj)
{
   int rc_gmdDomainCheckDone;
   jfieldID fid;
   u64_t pgmd;
   jclass cls = (*env)->GetObjectClass(env, obj);
   fid = (*env)->GetFieldID(env, cls, "gmdPtr", "J");
   if (fid == NULL) return 0;
   pgmd.i = (*env)->GetLongField(env, obj, fid);
   rc_gmdDomainCheckDone = gmdDomainCheckDone((gmdHandle_t)pgmd.p);
   return rc_gmdDomainCheckDone;
}

JNIEXPORT jboolean JNICALL Java_com_gams_api_gmd_GetFirstDVInNextSymbol(JNIEnv *env, jobject obj, jlong dvHandle, jbooleanArray nextavail)
{
   int rc_gmdGetFirstDVInNextSymbol;
   jfieldID fid;
   u64_t pgmd;
   jclass cls = (*env)->GetObjectClass(env, obj);
   u64_t local_dvHandle;
   jboolean *local_nextavail;
   int ib_nextavail = 0;
   fid = (*env)->GetFieldID(env, cls, "gmdPtr", "J");
   if (fid == NULL) return 0;
   pgmd.i = (*env)->GetLongField(env, obj, fid);
   local_dvHandle.i = dvHandle;
   local_nextavail = (*env)->GetBooleanArrayElements(env, nextavail, NULL);
   if(local_nextavail[0]) ib_nextavail = 1;
   rc_gmdGetFirstDVInNextSymbol = gmdGetFirstDVInNextSymbol((gmdHandle_t)pgmd.p, local_dvHandle.p, &ib_nextavail);
   if(ib_nextavail) local_nextavail[0] = JNI_TRUE; else local_nextavail[0] = JNI_FALSE;
   (*env)->ReleaseBooleanArrayElements(env, nextavail, local_nextavail, 0);
   return rc_gmdGetFirstDVInNextSymbol;
}

JNIEXPORT jboolean JNICALL Java_com_gams_api_gmd_MoveNextDVInSymbol(JNIEnv *env, jobject obj, jlong dvHandle, jbooleanArray nextavail)
{
   int rc_gmdMoveNextDVInSymbol;
   jfieldID fid;
   u64_t pgmd;
   jclass cls = (*env)->GetObjectClass(env, obj);
   u64_t local_dvHandle;
   jboolean *local_nextavail;
   int ib_nextavail = 0;
   fid = (*env)->GetFieldID(env, cls, "gmdPtr", "J");
   if (fid == NULL) return 0;
   pgmd.i = (*env)->GetLongField(env, obj, fid);
   local_dvHandle.i = dvHandle;
   local_nextavail = (*env)->GetBooleanArrayElements(env, nextavail, NULL);
   if(local_nextavail[0]) ib_nextavail = 1;
   rc_gmdMoveNextDVInSymbol = gmdMoveNextDVInSymbol((gmdHandle_t)pgmd.p, local_dvHandle.p, &ib_nextavail);
   if(ib_nextavail) local_nextavail[0] = JNI_TRUE; else local_nextavail[0] = JNI_FALSE;
   (*env)->ReleaseBooleanArrayElements(env, nextavail, local_nextavail, 0);
   return rc_gmdMoveNextDVInSymbol;
}

JNIEXPORT jboolean JNICALL Java_com_gams_api_gmd_FreeDVHandle(JNIEnv *env, jobject obj, jlong dvHandle)
{
   int rc_gmdFreeDVHandle;
   jfieldID fid;
   u64_t pgmd;
   jclass cls = (*env)->GetObjectClass(env, obj);
   u64_t local_dvHandle;
   fid = (*env)->GetFieldID(env, cls, "gmdPtr", "J");
   if (fid == NULL) return 0;
   pgmd.i = (*env)->GetLongField(env, obj, fid);
   local_dvHandle.i = dvHandle;
   rc_gmdFreeDVHandle = gmdFreeDVHandle((gmdHandle_t)pgmd.p, local_dvHandle.p);
   return rc_gmdFreeDVHandle;
}

JNIEXPORT jboolean JNICALL Java_com_gams_api_gmd_GetDVSymbol(JNIEnv *env, jobject obj, jlong dvHandle, jlongArray symPtr)
{
   int rc_gmdGetDVSymbol;
   jfieldID fid;
   u64_t pgmd;
   jclass cls = (*env)->GetObjectClass(env, obj);
   u64_t local_dvHandle;
   jlong* local_symPtr;
   void** localCopy_symPtr;
   fid = (*env)->GetFieldID(env, cls, "gmdPtr", "J");
   if (fid == NULL) return 0;
   pgmd.i = (*env)->GetLongField(env, obj, fid);
   local_dvHandle.i = dvHandle;
   local_symPtr = (*env)->GetLongArrayElements(env, symPtr, NULL);
   if( sizeof(jlong) != sizeof(void*) ) {
     jsize localCount;
     u64_t blab;
     localCopy_symPtr = (void**)malloc(sizeof(void*) * (*env)->GetArrayLength(env, symPtr));
     for( localCount = 0; localCount < (*env)->GetArrayLength(env, symPtr); ++localCount ) {
       blab.i = local_symPtr[localCount];
       localCopy_symPtr[localCount] = blab.p;
       }
   } else
     localCopy_symPtr = (void**)local_symPtr;
   rc_gmdGetDVSymbol = gmdGetDVSymbol((gmdHandle_t)pgmd.p, local_dvHandle.p, localCopy_symPtr);
   (*env)->ReleaseLongArrayElements(env, symPtr, local_symPtr, 0);
   if( sizeof(jlong) != sizeof(void*) ) {
     jsize localCount;
     u64_t blub;
     for( localCount = 0; localCount < (*env)->GetArrayLength(env, symPtr); ++localCount ) {
       blub.i = 0; blub.p = localCopy_symPtr[localCount];
       (*env)->SetLongArrayRegion(env, symPtr, localCount, 1, &blub.i);
     }
     free(localCopy_symPtr);
   }
   return rc_gmdGetDVSymbol;
}

JNIEXPORT jlong JNICALL Java_com_gams_api_gmd_GetDVSymbolPy(JNIEnv *env, jobject obj, jlong dvHandle, jbooleanArray status)
{
   u64_t rc_gmdGetDVSymbolPy;
   jfieldID fid;
   u64_t pgmd;
   jclass cls = (*env)->GetObjectClass(env, obj);
   u64_t local_dvHandle;
   jboolean *local_status;
   int ib_status = 0;
   fid = (*env)->GetFieldID(env, cls, "gmdPtr", "J");
   if (fid == NULL) return (jlong) NULL;
   pgmd.i = (*env)->GetLongField(env, obj, fid);
   local_dvHandle.i = dvHandle;
   local_status = (*env)->GetBooleanArrayElements(env, status, NULL);
   if(local_status[0]) ib_status = 1;
   rc_gmdGetDVSymbolPy.p = gmdGetDVSymbolPy((gmdHandle_t)pgmd.p, local_dvHandle.p, &ib_status);
   if(ib_status) local_status[0] = JNI_TRUE; else local_status[0] = JNI_FALSE;
   (*env)->ReleaseBooleanArrayElements(env, status, local_status, 0);
   return rc_gmdGetDVSymbolPy.i;
}

JNIEXPORT jboolean JNICALL Java_com_gams_api_gmd_GetDVSymbolRecord(JNIEnv *env, jobject obj, jlong dvHandle, jlongArray symIterPtr)
{
   int rc_gmdGetDVSymbolRecord;
   jfieldID fid;
   u64_t pgmd;
   jclass cls = (*env)->GetObjectClass(env, obj);
   u64_t local_dvHandle;
   jlong* local_symIterPtr;
   void** localCopy_symIterPtr;
   fid = (*env)->GetFieldID(env, cls, "gmdPtr", "J");
   if (fid == NULL) return 0;
   pgmd.i = (*env)->GetLongField(env, obj, fid);
   local_dvHandle.i = dvHandle;
   local_symIterPtr = (*env)->GetLongArrayElements(env, symIterPtr, NULL);
   if( sizeof(jlong) != sizeof(void*) ) {
     jsize localCount;
     u64_t blab;
     localCopy_symIterPtr = (void**)malloc(sizeof(void*) * (*env)->GetArrayLength(env, symIterPtr));
     for( localCount = 0; localCount < (*env)->GetArrayLength(env, symIterPtr); ++localCount ) {
       blab.i = local_symIterPtr[localCount];
       localCopy_symIterPtr[localCount] = blab.p;
       }
   } else
     localCopy_symIterPtr = (void**)local_symIterPtr;
   rc_gmdGetDVSymbolRecord = gmdGetDVSymbolRecord((gmdHandle_t)pgmd.p, local_dvHandle.p, localCopy_symIterPtr);
   (*env)->ReleaseLongArrayElements(env, symIterPtr, local_symIterPtr, 0);
   if( sizeof(jlong) != sizeof(void*) ) {
     jsize localCount;
     u64_t blub;
     for( localCount = 0; localCount < (*env)->GetArrayLength(env, symIterPtr); ++localCount ) {
       blub.i = 0; blub.p = localCopy_symIterPtr[localCount];
       (*env)->SetLongArrayRegion(env, symIterPtr, localCount, 1, &blub.i);
     }
     free(localCopy_symIterPtr);
   }
   return rc_gmdGetDVSymbolRecord;
}

JNIEXPORT jlong JNICALL Java_com_gams_api_gmd_GetDVSymbolRecordPy(JNIEnv *env, jobject obj, jlong dvHandle, jbooleanArray status)
{
   u64_t rc_gmdGetDVSymbolRecordPy;
   jfieldID fid;
   u64_t pgmd;
   jclass cls = (*env)->GetObjectClass(env, obj);
   u64_t local_dvHandle;
   jboolean *local_status;
   int ib_status = 0;
   fid = (*env)->GetFieldID(env, cls, "gmdPtr", "J");
   if (fid == NULL) return (jlong) NULL;
   pgmd.i = (*env)->GetLongField(env, obj, fid);
   local_dvHandle.i = dvHandle;
   local_status = (*env)->GetBooleanArrayElements(env, status, NULL);
   if(local_status[0]) ib_status = 1;
   rc_gmdGetDVSymbolRecordPy.p = gmdGetDVSymbolRecordPy((gmdHandle_t)pgmd.p, local_dvHandle.p, &ib_status);
   if(ib_status) local_status[0] = JNI_TRUE; else local_status[0] = JNI_FALSE;
   (*env)->ReleaseBooleanArrayElements(env, status, local_status, 0);
   return rc_gmdGetDVSymbolRecordPy.i;
}

JNIEXPORT jboolean JNICALL Java_com_gams_api_gmd_GetDVIndicator(JNIEnv *env, jobject obj, jlong dvHandle, jintArray viol)
{
   int rc_gmdGetDVIndicator;
   jfieldID fid;
   u64_t pgmd;
   jclass cls = (*env)->GetObjectClass(env, obj);
   u64_t local_dvHandle;
   int *local_viol;
   fid = (*env)->GetFieldID(env, cls, "gmdPtr", "J");
   if (fid == NULL) return 0;
   pgmd.i = (*env)->GetLongField(env, obj, fid);
   local_dvHandle.i = dvHandle;
   local_viol = (*env)->GetIntArrayElements(env, viol, NULL);
   rc_gmdGetDVIndicator = gmdGetDVIndicator((gmdHandle_t)pgmd.p, local_dvHandle.p, local_viol);
   (*env)->ReleaseIntArrayElements(env, viol, local_viol, 0);
   return rc_gmdGetDVIndicator;
}

JNIEXPORT jboolean JNICALL Java_com_gams_api_gmd_InitUpdate(JNIEnv *env, jobject obj, jlong gmoPtr)
{
   int rc_gmdInitUpdate;
   jfieldID fid;
   u64_t pgmd;
   jclass cls = (*env)->GetObjectClass(env, obj);
   u64_t local_gmoPtr;
   fid = (*env)->GetFieldID(env, cls, "gmdPtr", "J");
   if (fid == NULL) return 0;
   pgmd.i = (*env)->GetLongField(env, obj, fid);
   local_gmoPtr.i = gmoPtr;
   rc_gmdInitUpdate = gmdInitUpdate((gmdHandle_t)pgmd.p, local_gmoPtr.p);
   return rc_gmdInitUpdate;
}

JNIEXPORT jboolean JNICALL Java_com_gams_api_gmd_UpdateModelSymbol(JNIEnv *env, jobject obj, jlong gamsSymPtr, jint actionType, jlong dataSymPtr, jint updateType, jintArray noMatchCnt)
{
   int rc_gmdUpdateModelSymbol;
   jfieldID fid;
   u64_t pgmd;
   jclass cls = (*env)->GetObjectClass(env, obj);
   u64_t local_gamsSymPtr;
   u64_t local_dataSymPtr;
   int *local_noMatchCnt;
   fid = (*env)->GetFieldID(env, cls, "gmdPtr", "J");
   if (fid == NULL) return 0;
   pgmd.i = (*env)->GetLongField(env, obj, fid);
   local_gamsSymPtr.i = gamsSymPtr;
   local_dataSymPtr.i = dataSymPtr;
   local_noMatchCnt = (*env)->GetIntArrayElements(env, noMatchCnt, NULL);
   rc_gmdUpdateModelSymbol = gmdUpdateModelSymbol((gmdHandle_t)pgmd.p, local_gamsSymPtr.p, actionType, local_dataSymPtr.p, updateType, local_noMatchCnt);
   (*env)->ReleaseIntArrayElements(env, noMatchCnt, local_noMatchCnt, 0);
   return rc_gmdUpdateModelSymbol;
}

JNIEXPORT jboolean JNICALL Java_com_gams_api_gmd_CallSolver(JNIEnv *env, jobject obj, jstring solvername)
{
   int rc_gmdCallSolver;
   jfieldID fid;
   u64_t pgmd;
   jclass cls = (*env)->GetObjectClass(env, obj);
   char *local_solvername;
   fid = (*env)->GetFieldID(env, cls, "gmdPtr", "J");
   if (fid == NULL) return 0;
   pgmd.i = (*env)->GetLongField(env, obj, fid);
   local_solvername = (char *)(*env)->GetStringUTFChars(env, solvername, NULL);
   rc_gmdCallSolver = gmdCallSolver((gmdHandle_t)pgmd.p, local_solvername);
   (*env)->ReleaseStringUTFChars(env, solvername, local_solvername);
   return rc_gmdCallSolver;
}

JNIEXPORT jboolean JNICALL Java_com_gams_api_gmd_CallSolverTimed(JNIEnv *env, jobject obj, jstring solvername, jdoubleArray time)
{
   int rc_gmdCallSolverTimed;
   jfieldID fid;
   u64_t pgmd;
   jclass cls = (*env)->GetObjectClass(env, obj);
   char *local_solvername;
   double local_time[1];
   fid = (*env)->GetFieldID(env, cls, "gmdPtr", "J");
   if (fid == NULL) return 0;
   pgmd.i = (*env)->GetLongField(env, obj, fid);
   local_solvername = (char *)(*env)->GetStringUTFChars(env, solvername, NULL);
   rc_gmdCallSolverTimed = gmdCallSolverTimed((gmdHandle_t)pgmd.p, local_solvername, local_time);
   (*env)->ReleaseStringUTFChars(env, solvername, local_solvername);
   (*env)->SetDoubleArrayRegion(env, time, 0, 1, local_time);
   return rc_gmdCallSolverTimed;
}

JNIEXPORT jboolean JNICALL Java_com_gams_api_gmd_DenseSymbolToDenseArray(JNIEnv *env, jobject obj, jlong cube, jintArray vDim, jlong symPtr, jint field)
{
   int rc_gmdDenseSymbolToDenseArray;
   jfieldID fid;
   u64_t pgmd;
   jclass cls = (*env)->GetObjectClass(env, obj);
   u64_t local_cube;
   int *local_vDim;
   u64_t local_symPtr;
   fid = (*env)->GetFieldID(env, cls, "gmdPtr", "J");
   if (fid == NULL) return 0;
   pgmd.i = (*env)->GetLongField(env, obj, fid);
   local_cube.i = cube;
   local_vDim = (*env)->GetIntArrayElements(env, vDim, NULL);
   local_symPtr.i = symPtr;
   rc_gmdDenseSymbolToDenseArray = gmdDenseSymbolToDenseArray((gmdHandle_t)pgmd.p, local_cube.p, local_vDim, local_symPtr.p, field);
   (*env)->ReleaseIntArrayElements(env, vDim, local_vDim, 0);
   return rc_gmdDenseSymbolToDenseArray;
}

JNIEXPORT jboolean JNICALL Java_com_gams_api_gmd_SparseSymbolToDenseArray(JNIEnv *env, jobject obj, jlong cube, jintArray vDim, jlong symPtr, jlongArray vDomPtr, jint field, jintArray nDropped)
{
   int rc_gmdSparseSymbolToDenseArray;
   jfieldID fid;
   u64_t pgmd;
   jclass cls = (*env)->GetObjectClass(env, obj);
   u64_t local_cube;
   int *local_vDim;
   u64_t local_symPtr;
   jlong* local_vDomPtr;
   void** localCopy_vDomPtr;
   int local_nDropped[1];
   fid = (*env)->GetFieldID(env, cls, "gmdPtr", "J");
   if (fid == NULL) return 0;
   pgmd.i = (*env)->GetLongField(env, obj, fid);
   local_cube.i = cube;
   local_vDim = (*env)->GetIntArrayElements(env, vDim, NULL);
   local_symPtr.i = symPtr;
   local_vDomPtr = (*env)->GetLongArrayElements(env, vDomPtr, NULL);
   if( sizeof(jlong) != sizeof(void*) ) {
     jsize localCount;
     u64_t blab;
     localCopy_vDomPtr = (void**)malloc(sizeof(void*) * (*env)->GetArrayLength(env, vDomPtr));
     for( localCount = 0; localCount < (*env)->GetArrayLength(env, vDomPtr); ++localCount ) {
       blab.i = local_vDomPtr[localCount];
       localCopy_vDomPtr[localCount] = blab.p;
       }
   } else
     localCopy_vDomPtr = (void**)local_vDomPtr;
   rc_gmdSparseSymbolToDenseArray = gmdSparseSymbolToDenseArray((gmdHandle_t)pgmd.p, local_cube.p, local_vDim, local_symPtr.p, localCopy_vDomPtr, field, local_nDropped);
   (*env)->ReleaseIntArrayElements(env, vDim, local_vDim, 0);
   (*env)->ReleaseLongArrayElements(env, vDomPtr, local_vDomPtr, 0);
   if( sizeof(jlong) != sizeof(void*) ) {
     jsize localCount;
     u64_t blub;
     for( localCount = 0; localCount < (*env)->GetArrayLength(env, vDomPtr); ++localCount ) {
       blub.i = 0; blub.p = localCopy_vDomPtr[localCount];
       (*env)->SetLongArrayRegion(env, vDomPtr, localCount, 1, &blub.i);
     }
     free(localCopy_vDomPtr);
   }
   (*env)->SetIntArrayRegion(env, nDropped, 0, 1, local_nDropped);
   return rc_gmdSparseSymbolToDenseArray;
}

JNIEXPORT jboolean JNICALL Java_com_gams_api_gmd_SparseSymbolToSqzdArray(JNIEnv *env, jobject obj, jlong cube, jintArray vDim, jlong symPtr, jlongArray vDomSqueezePtr, jlongArray vDomPtr, jint field, jintArray nDropped)
{
   int rc_gmdSparseSymbolToSqzdArray;
   jfieldID fid;
   u64_t pgmd;
   jclass cls = (*env)->GetObjectClass(env, obj);
   u64_t local_cube;
   int *local_vDim;
   u64_t local_symPtr;
   jlong* local_vDomSqueezePtr;
   void** localCopy_vDomSqueezePtr;
   jlong* local_vDomPtr;
   void** localCopy_vDomPtr;
   int local_nDropped[1];
   fid = (*env)->GetFieldID(env, cls, "gmdPtr", "J");
   if (fid == NULL) return 0;
   pgmd.i = (*env)->GetLongField(env, obj, fid);
   local_cube.i = cube;
   local_vDim = (*env)->GetIntArrayElements(env, vDim, NULL);
   local_symPtr.i = symPtr;
   local_vDomSqueezePtr = (*env)->GetLongArrayElements(env, vDomSqueezePtr, NULL);
   if( sizeof(jlong) != sizeof(void*) ) {
     jsize localCount;
     u64_t blab;
     localCopy_vDomSqueezePtr = (void**)malloc(sizeof(void*) * (*env)->GetArrayLength(env, vDomSqueezePtr));
     for( localCount = 0; localCount < (*env)->GetArrayLength(env, vDomSqueezePtr); ++localCount ) {
       blab.i = local_vDomSqueezePtr[localCount];
       localCopy_vDomSqueezePtr[localCount] = blab.p;
       }
   } else
     localCopy_vDomSqueezePtr = (void**)local_vDomSqueezePtr;
   local_vDomPtr = (*env)->GetLongArrayElements(env, vDomPtr, NULL);
   if( sizeof(jlong) != sizeof(void*) ) {
     jsize localCount;
     u64_t blab;
     localCopy_vDomPtr = (void**)malloc(sizeof(void*) * (*env)->GetArrayLength(env, vDomPtr));
     for( localCount = 0; localCount < (*env)->GetArrayLength(env, vDomPtr); ++localCount ) {
       blab.i = local_vDomPtr[localCount];
       localCopy_vDomPtr[localCount] = blab.p;
       }
   } else
     localCopy_vDomPtr = (void**)local_vDomPtr;
   rc_gmdSparseSymbolToSqzdArray = gmdSparseSymbolToSqzdArray((gmdHandle_t)pgmd.p, local_cube.p, local_vDim, local_symPtr.p, localCopy_vDomSqueezePtr, localCopy_vDomPtr, field, local_nDropped);
   (*env)->ReleaseIntArrayElements(env, vDim, local_vDim, 0);
   (*env)->ReleaseLongArrayElements(env, vDomSqueezePtr, local_vDomSqueezePtr, 0);
   if( sizeof(jlong) != sizeof(void*) ) {
     jsize localCount;
     u64_t blub;
     for( localCount = 0; localCount < (*env)->GetArrayLength(env, vDomSqueezePtr); ++localCount ) {
       blub.i = 0; blub.p = localCopy_vDomSqueezePtr[localCount];
       (*env)->SetLongArrayRegion(env, vDomSqueezePtr, localCount, 1, &blub.i);
     }
     free(localCopy_vDomSqueezePtr);
   }
   (*env)->ReleaseLongArrayElements(env, vDomPtr, local_vDomPtr, 0);
   if( sizeof(jlong) != sizeof(void*) ) {
     jsize localCount;
     u64_t blub;
     for( localCount = 0; localCount < (*env)->GetArrayLength(env, vDomPtr); ++localCount ) {
       blub.i = 0; blub.p = localCopy_vDomPtr[localCount];
       (*env)->SetLongArrayRegion(env, vDomPtr, localCount, 1, &blub.i);
     }
     free(localCopy_vDomPtr);
   }
   (*env)->SetIntArrayRegion(env, nDropped, 0, 1, local_nDropped);
   return rc_gmdSparseSymbolToSqzdArray;
}

JNIEXPORT jboolean JNICALL Java_com_gams_api_gmd_DenseArrayToSymbol(JNIEnv *env, jobject obj, jlong symPtr, jlongArray vDomPtr, jlong cube, jintArray vDim)
{
   int rc_gmdDenseArrayToSymbol;
   jfieldID fid;
   u64_t pgmd;
   jclass cls = (*env)->GetObjectClass(env, obj);
   u64_t local_symPtr;
   jlong* local_vDomPtr;
   void** localCopy_vDomPtr;
   u64_t local_cube;
   int *local_vDim;
   fid = (*env)->GetFieldID(env, cls, "gmdPtr", "J");
   if (fid == NULL) return 0;
   pgmd.i = (*env)->GetLongField(env, obj, fid);
   local_symPtr.i = symPtr;
   local_vDomPtr = (*env)->GetLongArrayElements(env, vDomPtr, NULL);
   if( sizeof(jlong) != sizeof(void*) ) {
     jsize localCount;
     u64_t blab;
     localCopy_vDomPtr = (void**)malloc(sizeof(void*) * (*env)->GetArrayLength(env, vDomPtr));
     for( localCount = 0; localCount < (*env)->GetArrayLength(env, vDomPtr); ++localCount ) {
       blab.i = local_vDomPtr[localCount];
       localCopy_vDomPtr[localCount] = blab.p;
       }
   } else
     localCopy_vDomPtr = (void**)local_vDomPtr;
   local_cube.i = cube;
   local_vDim = (*env)->GetIntArrayElements(env, vDim, NULL);
   rc_gmdDenseArrayToSymbol = gmdDenseArrayToSymbol((gmdHandle_t)pgmd.p, local_symPtr.p, localCopy_vDomPtr, local_cube.p, local_vDim);
   (*env)->ReleaseLongArrayElements(env, vDomPtr, local_vDomPtr, 0);
   if( sizeof(jlong) != sizeof(void*) ) {
     jsize localCount;
     u64_t blub;
     for( localCount = 0; localCount < (*env)->GetArrayLength(env, vDomPtr); ++localCount ) {
       blub.i = 0; blub.p = localCopy_vDomPtr[localCount];
       (*env)->SetLongArrayRegion(env, vDomPtr, localCount, 1, &blub.i);
     }
     free(localCopy_vDomPtr);
   }
   (*env)->ReleaseIntArrayElements(env, vDim, local_vDim, 0);
   return rc_gmdDenseArrayToSymbol;
}

JNIEXPORT jboolean JNICALL Java_com_gams_api_gmd_DenseArraySlicesToSymbol(JNIEnv *env, jobject obj, jlong symPtr, jlongArray vDomSlicePtr, jlongArray vDomPtr, jlong cube, jintArray vDim)
{
   int rc_gmdDenseArraySlicesToSymbol;
   jfieldID fid;
   u64_t pgmd;
   jclass cls = (*env)->GetObjectClass(env, obj);
   u64_t local_symPtr;
   jlong* local_vDomSlicePtr;
   void** localCopy_vDomSlicePtr;
   jlong* local_vDomPtr;
   void** localCopy_vDomPtr;
   u64_t local_cube;
   int *local_vDim;
   fid = (*env)->GetFieldID(env, cls, "gmdPtr", "J");
   if (fid == NULL) return 0;
   pgmd.i = (*env)->GetLongField(env, obj, fid);
   local_symPtr.i = symPtr;
   local_vDomSlicePtr = (*env)->GetLongArrayElements(env, vDomSlicePtr, NULL);
   if( sizeof(jlong) != sizeof(void*) ) {
     jsize localCount;
     u64_t blab;
     localCopy_vDomSlicePtr = (void**)malloc(sizeof(void*) * (*env)->GetArrayLength(env, vDomSlicePtr));
     for( localCount = 0; localCount < (*env)->GetArrayLength(env, vDomSlicePtr); ++localCount ) {
       blab.i = local_vDomSlicePtr[localCount];
       localCopy_vDomSlicePtr[localCount] = blab.p;
       }
   } else
     localCopy_vDomSlicePtr = (void**)local_vDomSlicePtr;
   local_vDomPtr = (*env)->GetLongArrayElements(env, vDomPtr, NULL);
   if( sizeof(jlong) != sizeof(void*) ) {
     jsize localCount;
     u64_t blab;
     localCopy_vDomPtr = (void**)malloc(sizeof(void*) * (*env)->GetArrayLength(env, vDomPtr));
     for( localCount = 0; localCount < (*env)->GetArrayLength(env, vDomPtr); ++localCount ) {
       blab.i = local_vDomPtr[localCount];
       localCopy_vDomPtr[localCount] = blab.p;
       }
   } else
     localCopy_vDomPtr = (void**)local_vDomPtr;
   local_cube.i = cube;
   local_vDim = (*env)->GetIntArrayElements(env, vDim, NULL);
   rc_gmdDenseArraySlicesToSymbol = gmdDenseArraySlicesToSymbol((gmdHandle_t)pgmd.p, local_symPtr.p, localCopy_vDomSlicePtr, localCopy_vDomPtr, local_cube.p, local_vDim);
   (*env)->ReleaseLongArrayElements(env, vDomSlicePtr, local_vDomSlicePtr, 0);
   if( sizeof(jlong) != sizeof(void*) ) {
     jsize localCount;
     u64_t blub;
     for( localCount = 0; localCount < (*env)->GetArrayLength(env, vDomSlicePtr); ++localCount ) {
       blub.i = 0; blub.p = localCopy_vDomSlicePtr[localCount];
       (*env)->SetLongArrayRegion(env, vDomSlicePtr, localCount, 1, &blub.i);
     }
     free(localCopy_vDomSlicePtr);
   }
   (*env)->ReleaseLongArrayElements(env, vDomPtr, local_vDomPtr, 0);
   if( sizeof(jlong) != sizeof(void*) ) {
     jsize localCount;
     u64_t blub;
     for( localCount = 0; localCount < (*env)->GetArrayLength(env, vDomPtr); ++localCount ) {
       blub.i = 0; blub.p = localCopy_vDomPtr[localCount];
       (*env)->SetLongArrayRegion(env, vDomPtr, localCount, 1, &blub.i);
     }
     free(localCopy_vDomPtr);
   }
   (*env)->ReleaseIntArrayElements(env, vDim, local_vDim, 0);
   return rc_gmdDenseArraySlicesToSymbol;
}
